import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.newcomers": "Newcomers",
    "nav.schools": "Schools",
    "nav.employers": "Employers",
    "nav.agents": "Agents",
    "nav.visa_refusal": "Visa Refusal",
    "nav.visitor_visas": "Visitor Visas",
    "nav.pgwp": "PGWP",
    "nav.express_entry": "Express Entry & PR",
    "nav.iec": "IEC",
    "nav.get_started": "Get started",
    "nav.login": "Log in",
    "nav.account": "Account",
    "nav.sign_out": "Sign out",
    
    // Footer
    "footer.tagline": "Your trusted guide along your immigration journey.",
    "footer.services": "Services",
    "footer.about": "About",
    "footer.legal": "Legal",
    "footer.about_us": "About Us",
    "footer.contact": "Contact Us",
    "footer.careers": "Careers",
    "footer.terms": "Terms of Use",
    "footer.privacy": "Privacy Policy",
    "footer.accessibility": "Accessibility",
    "footer.rights": "All rights reserved.",
    "footer.education_agents": "Education Agents",

    // Index Page
    "index.hero.title": "Your trusted guide along your immigration journey",
    "index.hero.description": "Immipass is the clear and affordable platform for immigration guidance and legal support",
    "index.hero.cta.primary": "Get started",
    "index.hero.cta.secondary": "Talk to us",
    "index.steps.title": "Students, workers, and visitors: Immipass is with you at every step",
    "index.step1.title": "Apply for your visa",
    "index.step1.description": "Navigate the immigration process with clear understanding and automatic updates",
    "index.step2.title": "Submit for lawyer review",
    "index.step2.description": "Get guidance and expertise from expert immigration lawyers",
    "index.step3.title": "Stay organized",
    "index.step3.description": "Keep your critical documents organized in your personal Document Vault",
    "index.step4.title": "Continue your journey",
    "index.step4.description": "Plan your path to permanent residence with expert legal guidance",
    "index.features.title": "Exclusive benefits for Immipass Members",
    "index.features.subtitle": "Why Immipass?",
    "index.feature1.title": "Expert Legal Guidance",
    "index.feature1.description": "Access to leading immigration lawyers helps you navigate the immigration process",
    "index.feature2.title": "Stay Protected",
    "index.feature2.description": "Immipass will remind you of upcoming deadlines and legal updates",
    "index.feature3.title": "Unwavering Support",
    "index.feature3.description": "Licensed immigration lawyers working for you at every stage",
    "index.feature4.title": "Affordable Access",
    "index.feature4.description": "Every application is reviewed by a licensed immigration lawyer",
    "index.feature5.title": "Document Organization",
    "index.feature5.description": "Keep your critical documents organized in your personal vault",
    "index.feature6.title": "Exclusive Benefits",
    "index.feature6.description": "Get great deals on banking, mobile, internet, and more",
    "index.testimonials.title": "Trusted by thousands of international students, newcomers, and institutions",
    "index.testimonial1.quote": "The IRCC portal can be overwhelming to use at times, so I'm grateful that Immipass was able to help with reviewing and submitting my application.",
    "index.testimonial1.author": "Aisha",
    "index.testimonial1.role": "International Student from Nigeria",
    "index.testimonial2.quote": "I have a lot of friends and they already know they are going to use Immipass because it's convenient, interactive and made my life so much easier.",
    "index.testimonial2.author": "Ahmed",
    "index.testimonial2.role": "International Student from Pakistan",
    "index.testimonial3.quote": "I am so thankful to be here in Canada. I'm grateful for the effort, knowledge, and support of Immipass—you helped get me here!",
    "index.testimonial3.author": "Anagha",
    "index.testimonial3.role": "International Student from Kenya",
    "index.cta.title": "Take the next step",
    "index.cta.description": "Become a Immipass member today",
    "index.cta.primary": "Join Immipass",
    "index.cta.secondary": "Get in touch",

    // Newcomers Page
    "newcomers.hero.title": "Trusted guidance for your immigration journey",
    "newcomers.hero.description": "Affordable legal support to manage your immigration pathway from study, to work, to settlement.",
    "newcomers.hero.cta.primary": "Become a Immipass Member",
    "newcomers.hero.cta.secondary": "Log in now",
    "newcomers.features.title": "Immipass combines smart tools with lawyer guidance to help you navigate immigration affordably",
    "newcomers.features.subtitle": "What is Immipass?",
    "newcomers.feature1.title": "Legal Support",
    "newcomers.feature1.description": "Get guidance from expert immigration lawyers to prepare your strongest application",
    "newcomers.feature2.title": "Stay Compliant",
    "newcomers.feature2.description": "Immipass will remind you of upcoming deadlines and legal updates",
    "newcomers.feature3.title": "Document Vault",
    "newcomers.feature3.description": "Keep your critical documents organized and on-hand",
    "newcomers.feature4.title": "Timely Updates",
    "newcomers.feature4.description": "Navigate the immigration process with automatic status updates",
    "newcomers.feature5.title": "Community Support",
    "newcomers.feature5.description": "Join thousands of successful newcomers who chose Immipass",
    "newcomers.feature6.title": "Settlement Services",
    "newcomers.feature6.description": "Get offers on banking, mobile, internet, and more",
    "newcomers.steps.title": "How It Works",
    "newcomers.steps.subtitle": "Your Path to Canada",
    "newcomers.step1.title": "Create Your Profile",
    "newcomers.step1.description": "Sign up and tell us about your immigration goals",
    "newcomers.step2.title": "Get Personalized Guidance",
    "newcomers.step2.description": "Receive step-by-step instructions tailored to your situation",
    "newcomers.step3.title": "Lawyer Review",
    "newcomers.step3.description": "Every application is reviewed by licensed immigration lawyers",
    "newcomers.step4.title": "Submit with Confidence",
    "newcomers.step4.description": "Submit your strongest possible application",
    "newcomers.cta.title": "Start your immigration journey today",
    "newcomers.cta.description": "Join thousands of newcomers who trust Immipass",
    "newcomers.cta.primary": "Get Started",

    // PGWP Page
    "pgwp.hero.title": "Stay, Work & Thrive: Apply for your PGWP with Immipass",
    "pgwp.hero.description": "Canada's Post-Graduation Work Permit lets international students stay and work after finishing their studies. Immipass combines legal expertise with a student-friendly platform to guide you through every part of the PGWP process.",
    "pgwp.hero.cta.primary": "Start Your PGWP Application",
    "pgwp.features.title": "Why choose Immipass for your PGWP?",
    "pgwp.features.subtitle": "Benefits",
    "pgwp.feature1.title": "Graduate Support",
    "pgwp.feature1.description": "Transition smoothly from student to work permit holder",
    "pgwp.feature2.title": "Work Experience",
    "pgwp.feature2.description": "Gain valuable Canadian work experience after graduation",
    "pgwp.feature3.title": "Easy Application",
    "pgwp.feature3.description": "Step-by-step guidance through your PGWP application",
    "pgwp.feature4.title": "Legal Review",
    "pgwp.feature4.description": "Every application reviewed by licensed immigration lawyers",
    "pgwp.feature5.title": "Timely Processing",
    "pgwp.feature5.description": "Apply within deadlines with automatic reminders",
    "pgwp.feature6.title": "PR Pathway",
    "pgwp.feature6.description": "Build towards permanent residence with work experience",
    "pgwp.steps.title": "How to Apply for Your PGWP",
    "pgwp.steps.subtitle": "Simple Steps",
    "pgwp.step1.title": "Check Eligibility",
    "pgwp.step1.description": "Verify you meet PGWP requirements",
    "pgwp.step2.title": "Gather Documents",
    "pgwp.step2.description": "Collect required documents with our checklist",
    "pgwp.step3.title": "Submit Application",
    "pgwp.step3.description": "Complete and submit with legal review",
    "pgwp.step4.title": "Start Working",
    "pgwp.step4.description": "Begin your Canadian career journey",
    "pgwp.cta.title": "Start your post-graduation journey",
    "pgwp.cta.description": "Apply for your PGWP with expert support",
    "pgwp.cta.primary": "Get Started",

    // Express Entry Page
    "express.hero.subtitle": "Your Fast Track to Canadian Permanent Residence:",
    "express.hero.title": "Immipass Express Entry",
    "express.hero.description": "Your future in Canada starts with the right first step. Immipass guides you through Express Entry with expert support, lawyer review, and long-term PR planning—all for just $600 plus government fees.",
    "express.hero.cta.primary": "Get Started",
    "express.features.title": "Immigrate to Canada with Affordable Legal Guidance",
    "express.features.subtitle": "What is Immipass?",
    "express.feature1.title": "Permanent Residence",
    "express.feature1.description": "Your pathway to becoming a Canadian permanent resident",
    "express.feature2.title": "Family Sponsorship",
    "express.feature2.description": "Bring your family to Canada with you",
    "express.feature3.title": "Profile Optimization",
    "express.feature3.description": "Maximize your CRS score with expert guidance",
    "express.feature4.title": "Legal Support",
    "express.feature4.description": "Full legal review for just $600 plus government fees",
    "express.feature5.title": "Long-term Planning",
    "express.feature5.description": "Strategic advice for your PR pathway",
    "express.feature6.title": "Expert Guidance",
    "express.feature6.description": "Backed by leading immigration lawyers",
    "express.steps.title": "Your Path to Permanent Residence",
    "express.steps.subtitle": "How It Works",
    "express.step1.title": "Assessment",
    "express.step1.description": "Evaluate your eligibility and CRS score",
    "express.step2.title": "Profile Creation",
    "express.step2.description": "Create your Express Entry profile",
    "express.step3.title": "ITA Application",
    "express.step3.description": "Apply when you receive an invitation",
    "express.step4.title": "Welcome to Canada",
    "express.step4.description": "Receive your permanent residence",
    "express.cta.title": "Start your Express Entry journey",
    "express.cta.description": "Begin your path to Canadian permanent residence",
    "express.cta.primary": "Get Started",

    // IEC Page
    "iec.hero.title": "Travel in Canada on a Working Holiday with IEC: International Experience Canada",
    "iec.hero.description": "IEC is a government program designed to help you gain international work experience, improve your language skills in English and French, and fund the trip of a lifetime.",
    "iec.hero.cta.primary": "Get Started with IEC",
    "iec.features.title": "Immipass combines smart tools with lawyer guidance",
    "iec.features.subtitle": "What is Immipass?",
    "iec.feature1.title": "Working Holiday",
    "iec.feature1.description": "Travel and work across Canada with an open work permit",
    "iec.feature2.title": "Work Experience",
    "iec.feature2.description": "Gain valuable international work experience",
    "iec.feature3.title": "Explore Canada",
    "iec.feature3.description": "Experience Canadian culture, nature, and adventure",
    "iec.feature4.title": "Legal Guidance",
    "iec.feature4.description": "Expert support through your IEC application",
    "iec.feature5.title": "Quick Start",
    "iec.feature5.description": "Create your profile for only CAD$75",
    "iec.feature6.title": "Free Eligibility Check",
    "iec.feature6.description": "See if you qualify before you apply",
    "iec.steps.title": "How to Apply for IEC",
    "iec.steps.subtitle": "Your Path to Adventure",
    "iec.step1.title": "Check Eligibility",
    "iec.step1.description": "See if you qualify for IEC for free",
    "iec.step2.title": "Create Profile",
    "iec.step2.description": "Submit your IEC profile for only CAD$75",
    "iec.step3.title": "Receive Invitation",
    "iec.step3.description": "Get invited to apply for your work permit",
    "iec.step4.title": "Start Your Adventure",
    "iec.step4.description": "Begin your Canadian working holiday",
    "iec.cta.title": "Start your Canadian adventure",
    "iec.cta.description": "Apply for IEC with expert support",
    "iec.cta.primary": "Check Your Eligibility",

    // Visitor Visas Page
    "visitor.hero.title": "Travel with Confidence: Apply for Your Visitor Visa or Super Visa with Immipass",
    "visitor.hero.description": "Whether you're reconnecting with loved ones, exploring new places, or traveling for business, Immipass makes applying for your visitor visa clear and affordable. Visitor visa applications are just $100 for a single applicant.",
    "visitor.hero.cta.primary": "Get Started on Your Visit",
    "visitor.features.title": "Immipass makes visitor visa applications simple",
    "visitor.features.subtitle": "Why Choose Immipass?",
    "visitor.feature1.title": "Visitor Visas",
    "visitor.feature1.description": "Apply for temporary resident visas to visit Canada",
    "visitor.feature2.title": "Super Visa",
    "visitor.feature2.description": "Extended stays for parents and grandparents of Canadian residents",
    "visitor.feature3.title": "Simple Process",
    "visitor.feature3.description": "Clear, step-by-step guidance through your application",
    "visitor.feature4.title": "Legal Review",
    "visitor.feature4.description": "Every application reviewed by licensed immigration lawyers",
    "visitor.feature5.title": "Fast Processing",
    "visitor.feature5.description": "Efficient process to get you traveling sooner",
    "visitor.feature6.title": "Family Reunions",
    "visitor.feature6.description": "Reconnect with loved ones in Canada",
    "visitor.cta.title": "Start your Canadian visit today",
    "visitor.cta.description": "Apply for your visitor visa with expert support",
    "visitor.cta.primary": "Get Started",

    // Visa Refusal Page
    "refusal.hero.title": "Get Help After a Visa Refusal",
    "refusal.hero.description": "A visa refusal does not have to be the end of your journey. Immipass is the affordable and efficient way to explore all available options for approval.",
    "refusal.hero.cta.primary": "Get Help with a Visa Refusal",
    "refusal.features.title": "We help you understand your options and move forward",
    "refusal.features.subtitle": "What if my visa was refused?",
    "refusal.feature1.title": "Case Review",
    "refusal.feature1.description": "Our lawyers analyze your refusal letter to understand what went wrong",
    "refusal.feature2.title": "Legal Assessment",
    "refusal.feature2.description": "Get professional advice on your options moving forward",
    "refusal.feature3.title": "Reapplication Support",
    "refusal.feature3.description": "Strengthen your next application with expert guidance",
    "refusal.feature4.title": "Consultation",
    "refusal.feature4.description": "Discuss your case with experienced immigration lawyers",
    "refusal.feature5.title": "Appeal Options",
    "refusal.feature5.description": "Explore judicial review and other legal remedies",
    "refusal.feature6.title": "Timely Response",
    "refusal.feature6.description": "Act quickly within appeal deadlines",
    "refusal.cta.title": "Don't give up on your Canadian dream",
    "refusal.cta.description": "Get professional help to explore your options",
    "refusal.cta.primary": "Get Started",

    // Employers Page
    "employers.hero.title": "Optimize International Hiring. Reduce Costs. Stay Compliant.",
    "employers.hero.description": "Close skills gaps with the modern approach to global hiring—faster processing, lower costs, and higher success.",
    "employers.hero.cta.primary": "Talk to Us",
    "employers.hero.cta.secondary": "Book a Demo",
    "employers.features.title": "Immipass is the leading immigration management platform for employers",
    "employers.features.subtitle": "What is Immipass",
    "employers.feature1.title": "Streamlined Hiring",
    "employers.feature1.description": "Fast-track international hiring with our digital platform",
    "employers.feature2.title": "Reduce Costs",
    "employers.feature2.description": "Lower legal fees with efficient, technology-driven processes",
    "employers.feature3.title": "Stay Compliant",
    "employers.feature3.description": "Expert legal oversight ensures compliance with immigration laws",
    "employers.feature4.title": "Faster Processing",
    "employers.feature4.description": "Reduce processing times with automated workflows",
    "employers.feature5.title": "Retain Talent",
    "employers.feature5.description": "Support employees through their immigration journey",
    "employers.feature6.title": "Higher Success Rates",
    "employers.feature6.description": "Expert guidance leads to better outcomes",
    "employers.cta.title": "Start hiring global talent today",
    "employers.cta.description": "Modernize your international hiring with Immipass",
    "employers.cta.primary": "Get Started",
    "employers.cta.secondary": "Schedule a Demo",

    // Agents Page
    "agents.hero.title": "Give your students the advantage of trusted, affordable legal support",
    "agents.hero.description": "Offer lawyer-backed guidance without changing how you work with students.",
    "agents.hero.cta.primary": "Create Your Free Agent Account",
    "agents.hero.cta.secondary": "Book a Demo",
    "agents.features.title": "Immipass gives education agents trusted, affordable legal immigration support",
    "agents.features.subtitle": "What is Immipass?",
    "agents.feature1.title": "Legal Support",
    "agents.feature1.description": "Offer lawyer-backed guidance without changing how you work with students",
    "agents.feature2.title": "Reduce Risk",
    "agents.feature2.description": "Protect yourself and your students with professional legal oversight",
    "agents.feature3.title": "Better Outcomes",
    "agents.feature3.description": "Help your students succeed with comprehensive immigration support",
    "agents.feature4.title": "Affordable Pricing",
    "agents.feature4.description": "Competitive rates that work for agents and students",
    "agents.feature5.title": "Build Trust",
    "agents.feature5.description": "Strengthen your reputation with professional legal backing",
    "agents.feature6.title": "Partnership Model",
    "agents.feature6.description": "Continue guiding students while we handle legal complexities",
    "agents.cta.title": "Partner with Immipass today",
    "agents.cta.description": "Give your students the legal support they deserve",
    "agents.cta.primary": "Create Free Account",
    "agents.cta.secondary": "Learn More",

    // Institutions Page
    "institutions.hero.title": "Your partner for a better international student experience",
    "institutions.hero.description": "Immipass is the definitive digital platform for immigration management",
    "institutions.hero.cta.primary": "Partner with us",
    "institutions.hero.cta.secondary": "Book a demo",
    "institutions.features.title": "Immipass is the premier immigration management platform, powered by legal experts",
    "institutions.features.subtitle": "What is Immipass",
    "institutions.feature1.title": "Streamlined Operations",
    "institutions.feature1.description": "Manage all international student immigration needs in one platform",
    "institutions.feature2.title": "Student Success",
    "institutions.feature2.description": "Help students stay compliant and successful throughout their journey",
    "institutions.feature3.title": "Risk Mitigation",
    "institutions.feature3.description": "Reduce compliance risks with expert legal oversight",
    "institutions.feature4.title": "Improved Retention",
    "institutions.feature4.description": "Support students from admission through to graduation and beyond",
    "institutions.feature5.title": "Time Savings",
    "institutions.feature5.description": "Reduce administrative burden on your international office",
    "institutions.feature6.title": "Trusted Partner",
    "institutions.feature6.description": "Backed by leading immigration lawyers across Canada",
    "institutions.cta.title": "Transform your international student experience",
    "institutions.cta.description": "Partner with Immipass to provide comprehensive immigration support",
    "institutions.cta.primary": "Schedule a Demo",
    "institutions.cta.secondary": "Contact Us",
  },
  fr: {
    // Navbar
    "nav.newcomers": "Nouveaux arrivants",
    "nav.schools": "Écoles",
    "nav.employers": "Employeurs",
    "nav.agents": "Agents",
    "nav.visa_refusal": "Refus de visa",
    "nav.visitor_visas": "Visas visiteur",
    "nav.pgwp": "PTPD",
    "nav.express_entry": "Entrée express et RP",
    "nav.iec": "EIC",
    "nav.get_started": "Commencer",
    "nav.login": "Connexion",
    "nav.account": "Compte",
    "nav.sign_out": "Déconnexion",
    
    // Footer
    "footer.tagline": "Votre guide de confiance tout au long de votre parcours d'immigration.",
    "footer.services": "Services",
    "footer.about": "À propos",
    "footer.legal": "Mentions légales",
    "footer.about_us": "À propos de nous",
    "footer.contact": "Nous contacter",
    "footer.careers": "Carrières",
    "footer.terms": "Conditions d'utilisation",
    "footer.privacy": "Politique de confidentialité",
    "footer.accessibility": "Accessibilité",
    "footer.rights": "Tous droits réservés.",
    "footer.education_agents": "Agents d'éducation",

    // Index Page
    "index.hero.title": "Votre guide de confiance tout au long de votre parcours d'immigration",
    "index.hero.description": "Immipass est la plateforme claire et abordable pour l'orientation en immigration et le soutien juridique",
    "index.hero.cta.primary": "Commencer",
    "index.hero.cta.secondary": "Nous parler",
    "index.steps.title": "Étudiants, travailleurs et visiteurs : Immipass vous accompagne à chaque étape",
    "index.step1.title": "Faites votre demande de visa",
    "index.step1.description": "Naviguez dans le processus d'immigration avec une compréhension claire et des mises à jour automatiques",
    "index.step2.title": "Soumettez pour révision juridique",
    "index.step2.description": "Obtenez des conseils et l'expertise d'avocats spécialisés en immigration",
    "index.step3.title": "Restez organisé",
    "index.step3.description": "Gardez vos documents importants organisés dans votre coffre-fort personnel",
    "index.step4.title": "Poursuivez votre parcours",
    "index.step4.description": "Planifiez votre chemin vers la résidence permanente avec des conseils juridiques experts",
    "index.features.title": "Avantages exclusifs pour les membres Immipass",
    "index.features.subtitle": "Pourquoi Immipass?",
    "index.feature1.title": "Conseils juridiques experts",
    "index.feature1.description": "L'accès à des avocats en immigration de premier plan vous aide à naviguer dans le processus d'immigration",
    "index.feature2.title": "Restez protégé",
    "index.feature2.description": "Immipass vous rappellera les échéances et les mises à jour juridiques",
    "index.feature3.title": "Soutien indéfectible",
    "index.feature3.description": "Des avocats en immigration agréés travaillent pour vous à chaque étape",
    "index.feature4.title": "Accès abordable",
    "index.feature4.description": "Chaque demande est examinée par un avocat en immigration agréé",
    "index.feature5.title": "Organisation des documents",
    "index.feature5.description": "Gardez vos documents importants organisés dans votre coffre-fort personnel",
    "index.feature6.title": "Avantages exclusifs",
    "index.feature6.description": "Obtenez d'excellentes offres sur les services bancaires, mobiles, Internet et plus encore",
    "index.testimonials.title": "Approuvé par des milliers d'étudiants internationaux, de nouveaux arrivants et d'institutions",
    "index.testimonial1.quote": "Le portail d'IRCC peut être parfois difficile à utiliser, je suis donc reconnaissante qu'Immipass ait pu m'aider à réviser et soumettre ma demande.",
    "index.testimonial1.author": "Aisha",
    "index.testimonial1.role": "Étudiante internationale du Nigeria",
    "index.testimonial2.quote": "J'ai beaucoup d'amis et ils savent déjà qu'ils vont utiliser Immipass car c'est pratique, interactif et ça m'a tellement facilité la vie.",
    "index.testimonial2.author": "Ahmed",
    "index.testimonial2.role": "Étudiant international du Pakistan",
    "index.testimonial3.quote": "Je suis tellement reconnaissante d'être ici au Canada. Je suis reconnaissante pour les efforts, les connaissances et le soutien d'Immipass—vous m'avez aidée à arriver ici!",
    "index.testimonial3.author": "Anagha",
    "index.testimonial3.role": "Étudiante internationale du Kenya",
    "index.cta.title": "Passez à l'étape suivante",
    "index.cta.description": "Devenez membre Immipass aujourd'hui",
    "index.cta.primary": "Rejoindre Immipass",
    "index.cta.secondary": "Nous contacter",

    // Newcomers Page
    "newcomers.hero.title": "Des conseils de confiance pour votre parcours d'immigration",
    "newcomers.hero.description": "Un soutien juridique abordable pour gérer votre parcours d'immigration, des études au travail jusqu'à l'établissement.",
    "newcomers.hero.cta.primary": "Devenir membre Immipass",
    "newcomers.hero.cta.secondary": "Se connecter",
    "newcomers.features.title": "Immipass combine des outils intelligents avec des conseils juridiques pour vous aider à naviguer l'immigration de manière abordable",
    "newcomers.features.subtitle": "Qu'est-ce qu'Immipass?",
    "newcomers.feature1.title": "Soutien juridique",
    "newcomers.feature1.description": "Obtenez des conseils d'avocats experts en immigration pour préparer votre meilleure demande",
    "newcomers.feature2.title": "Restez conforme",
    "newcomers.feature2.description": "Immipass vous rappellera les échéances et les mises à jour juridiques",
    "newcomers.feature3.title": "Coffre-fort de documents",
    "newcomers.feature3.description": "Gardez vos documents importants organisés et à portée de main",
    "newcomers.feature4.title": "Mises à jour en temps opportun",
    "newcomers.feature4.description": "Naviguez dans le processus d'immigration avec des mises à jour automatiques",
    "newcomers.feature5.title": "Soutien communautaire",
    "newcomers.feature5.description": "Rejoignez des milliers de nouveaux arrivants qui ont choisi Immipass",
    "newcomers.feature6.title": "Services d'établissement",
    "newcomers.feature6.description": "Obtenez des offres sur les services bancaires, mobiles, Internet et plus encore",
    "newcomers.steps.title": "Comment ça marche",
    "newcomers.steps.subtitle": "Votre chemin vers le Canada",
    "newcomers.step1.title": "Créez votre profil",
    "newcomers.step1.description": "Inscrivez-vous et parlez-nous de vos objectifs d'immigration",
    "newcomers.step2.title": "Obtenez des conseils personnalisés",
    "newcomers.step2.description": "Recevez des instructions étape par étape adaptées à votre situation",
    "newcomers.step3.title": "Révision juridique",
    "newcomers.step3.description": "Chaque demande est examinée par des avocats en immigration agréés",
    "newcomers.step4.title": "Soumettez en toute confiance",
    "newcomers.step4.description": "Soumettez la meilleure demande possible",
    "newcomers.cta.title": "Commencez votre parcours d'immigration aujourd'hui",
    "newcomers.cta.description": "Rejoignez des milliers de nouveaux arrivants qui font confiance à Immipass",
    "newcomers.cta.primary": "Commencer",

    // PGWP Page
    "pgwp.hero.title": "Restez, travaillez et prospérez : Faites votre demande de PTPD avec Immipass",
    "pgwp.hero.description": "Le permis de travail post-diplôme du Canada permet aux étudiants internationaux de rester et de travailler après leurs études. Immipass combine l'expertise juridique avec une plateforme conviviale pour vous guider à travers chaque étape du processus PTPD.",
    "pgwp.hero.cta.primary": "Commencer votre demande de PTPD",
    "pgwp.features.title": "Pourquoi choisir Immipass pour votre PTPD?",
    "pgwp.features.subtitle": "Avantages",
    "pgwp.feature1.title": "Soutien aux diplômés",
    "pgwp.feature1.description": "Transition en douceur du statut d'étudiant à celui de titulaire de permis de travail",
    "pgwp.feature2.title": "Expérience de travail",
    "pgwp.feature2.description": "Acquérez une précieuse expérience de travail canadienne après vos études",
    "pgwp.feature3.title": "Demande facile",
    "pgwp.feature3.description": "Des conseils étape par étape pour votre demande de PTPD",
    "pgwp.feature4.title": "Révision juridique",
    "pgwp.feature4.description": "Chaque demande est examinée par des avocats en immigration agréés",
    "pgwp.feature5.title": "Traitement rapide",
    "pgwp.feature5.description": "Postulez dans les délais avec des rappels automatiques",
    "pgwp.feature6.title": "Chemin vers la RP",
    "pgwp.feature6.description": "Progressez vers la résidence permanente grâce à l'expérience de travail",
    "pgwp.steps.title": "Comment faire votre demande de PTPD",
    "pgwp.steps.subtitle": "Étapes simples",
    "pgwp.step1.title": "Vérifier l'admissibilité",
    "pgwp.step1.description": "Vérifiez que vous répondez aux exigences du PTPD",
    "pgwp.step2.title": "Rassembler les documents",
    "pgwp.step2.description": "Collectez les documents requis avec notre liste de contrôle",
    "pgwp.step3.title": "Soumettre la demande",
    "pgwp.step3.description": "Complétez et soumettez avec révision juridique",
    "pgwp.step4.title": "Commencer à travailler",
    "pgwp.step4.description": "Débutez votre carrière canadienne",
    "pgwp.cta.title": "Commencez votre parcours post-diplôme",
    "pgwp.cta.description": "Faites votre demande de PTPD avec un soutien expert",
    "pgwp.cta.primary": "Commencer",

    // Express Entry Page
    "express.hero.subtitle": "Votre voie rapide vers la résidence permanente au Canada:",
    "express.hero.title": "Immipass Entrée Express",
    "express.hero.description": "Votre avenir au Canada commence par la bonne première étape. Immipass vous guide à travers l'Entrée Express avec un soutien expert, une révision juridique et une planification à long terme de la RP—le tout pour seulement 600$ plus les frais gouvernementaux.",
    "express.hero.cta.primary": "Commencer",
    "express.features.title": "Immigrez au Canada avec des conseils juridiques abordables",
    "express.features.subtitle": "Qu'est-ce qu'Immipass?",
    "express.feature1.title": "Résidence permanente",
    "express.feature1.description": "Votre chemin pour devenir résident permanent canadien",
    "express.feature2.title": "Parrainage familial",
    "express.feature2.description": "Amenez votre famille au Canada avec vous",
    "express.feature3.title": "Optimisation du profil",
    "express.feature3.description": "Maximisez votre score CRS avec des conseils experts",
    "express.feature4.title": "Soutien juridique",
    "express.feature4.description": "Révision juridique complète pour seulement 600$ plus les frais gouvernementaux",
    "express.feature5.title": "Planification à long terme",
    "express.feature5.description": "Conseils stratégiques pour votre parcours vers la RP",
    "express.feature6.title": "Conseils d'experts",
    "express.feature6.description": "Soutenu par des avocats en immigration de premier plan",
    "express.steps.title": "Votre chemin vers la résidence permanente",
    "express.steps.subtitle": "Comment ça marche",
    "express.step1.title": "Évaluation",
    "express.step1.description": "Évaluez votre admissibilité et votre score CRS",
    "express.step2.title": "Création du profil",
    "express.step2.description": "Créez votre profil Entrée Express",
    "express.step3.title": "Demande ITA",
    "express.step3.description": "Postulez lorsque vous recevez une invitation",
    "express.step4.title": "Bienvenue au Canada",
    "express.step4.description": "Recevez votre résidence permanente",
    "express.cta.title": "Commencez votre parcours Entrée Express",
    "express.cta.description": "Débutez votre chemin vers la résidence permanente canadienne",
    "express.cta.primary": "Commencer",

    // IEC Page
    "iec.hero.title": "Voyagez au Canada avec un permis vacances-travail EIC: Expérience internationale Canada",
    "iec.hero.description": "EIC est un programme gouvernemental conçu pour vous aider à acquérir une expérience de travail internationale, améliorer vos compétences linguistiques en anglais et en français, et financer le voyage d'une vie.",
    "iec.hero.cta.primary": "Commencer avec EIC",
    "iec.features.title": "Immipass combine des outils intelligents avec des conseils juridiques",
    "iec.features.subtitle": "Qu'est-ce qu'Immipass?",
    "iec.feature1.title": "Vacances-travail",
    "iec.feature1.description": "Voyagez et travaillez à travers le Canada avec un permis de travail ouvert",
    "iec.feature2.title": "Expérience de travail",
    "iec.feature2.description": "Acquérez une précieuse expérience de travail internationale",
    "iec.feature3.title": "Explorez le Canada",
    "iec.feature3.description": "Découvrez la culture, la nature et l'aventure canadiennes",
    "iec.feature4.title": "Conseils juridiques",
    "iec.feature4.description": "Soutien expert pour votre demande EIC",
    "iec.feature5.title": "Démarrage rapide",
    "iec.feature5.description": "Créez votre profil pour seulement 75$ CAD",
    "iec.feature6.title": "Vérification d'admissibilité gratuite",
    "iec.feature6.description": "Vérifiez si vous êtes admissible avant de postuler",
    "iec.steps.title": "Comment postuler pour EIC",
    "iec.steps.subtitle": "Votre chemin vers l'aventure",
    "iec.step1.title": "Vérifier l'admissibilité",
    "iec.step1.description": "Vérifiez gratuitement si vous êtes admissible à EIC",
    "iec.step2.title": "Créer le profil",
    "iec.step2.description": "Soumettez votre profil EIC pour seulement 75$ CAD",
    "iec.step3.title": "Recevoir l'invitation",
    "iec.step3.description": "Recevez une invitation à postuler pour votre permis de travail",
    "iec.step4.title": "Commencer votre aventure",
    "iec.step4.description": "Débutez vos vacances-travail canadiennes",
    "iec.cta.title": "Commencez votre aventure canadienne",
    "iec.cta.description": "Postulez pour EIC avec un soutien expert",
    "iec.cta.primary": "Vérifier votre admissibilité",

    // Visitor Visas Page
    "visitor.hero.title": "Voyagez en toute confiance : Faites votre demande de visa visiteur ou Super Visa avec Immipass",
    "visitor.hero.description": "Que vous retrouviez des proches, exploriez de nouveaux endroits ou voyagiez pour affaires, Immipass rend la demande de visa visiteur claire et abordable. Les demandes de visa visiteur coûtent seulement 100$ pour un demandeur unique.",
    "visitor.hero.cta.primary": "Commencer votre visite",
    "visitor.features.title": "Immipass simplifie les demandes de visa visiteur",
    "visitor.features.subtitle": "Pourquoi choisir Immipass?",
    "visitor.feature1.title": "Visas visiteur",
    "visitor.feature1.description": "Postulez pour des visas de résident temporaire pour visiter le Canada",
    "visitor.feature2.title": "Super Visa",
    "visitor.feature2.description": "Séjours prolongés pour les parents et grands-parents de résidents canadiens",
    "visitor.feature3.title": "Processus simple",
    "visitor.feature3.description": "Des conseils clairs, étape par étape, pour votre demande",
    "visitor.feature4.title": "Révision juridique",
    "visitor.feature4.description": "Chaque demande est examinée par des avocats en immigration agréés",
    "visitor.feature5.title": "Traitement rapide",
    "visitor.feature5.description": "Un processus efficace pour vous faire voyager plus tôt",
    "visitor.feature6.title": "Réunions familiales",
    "visitor.feature6.description": "Retrouvez vos proches au Canada",
    "visitor.cta.title": "Commencez votre visite au Canada aujourd'hui",
    "visitor.cta.description": "Faites votre demande de visa visiteur avec un soutien expert",
    "visitor.cta.primary": "Commencer",

    // Visa Refusal Page
    "refusal.hero.title": "Obtenez de l'aide après un refus de visa",
    "refusal.hero.description": "Un refus de visa n'est pas forcément la fin de votre parcours. Immipass est le moyen abordable et efficace d'explorer toutes les options disponibles pour l'approbation.",
    "refusal.hero.cta.primary": "Obtenir de l'aide pour un refus de visa",
    "refusal.features.title": "Nous vous aidons à comprendre vos options et à avancer",
    "refusal.features.subtitle": "Et si mon visa a été refusé?",
    "refusal.feature1.title": "Révision du dossier",
    "refusal.feature1.description": "Nos avocats analysent votre lettre de refus pour comprendre ce qui s'est passé",
    "refusal.feature2.title": "Évaluation juridique",
    "refusal.feature2.description": "Obtenez des conseils professionnels sur vos options pour la suite",
    "refusal.feature3.title": "Soutien à la nouvelle demande",
    "refusal.feature3.description": "Renforcez votre prochaine demande avec des conseils experts",
    "refusal.feature4.title": "Consultation",
    "refusal.feature4.description": "Discutez de votre cas avec des avocats en immigration expérimentés",
    "refusal.feature5.title": "Options d'appel",
    "refusal.feature5.description": "Explorez la révision judiciaire et d'autres recours légaux",
    "refusal.feature6.title": "Réponse rapide",
    "refusal.feature6.description": "Agissez rapidement dans les délais d'appel",
    "refusal.cta.title": "N'abandonnez pas votre rêve canadien",
    "refusal.cta.description": "Obtenez une aide professionnelle pour explorer vos options",
    "refusal.cta.primary": "Commencer",

    // Employers Page
    "employers.hero.title": "Optimisez le recrutement international. Réduisez les coûts. Restez conforme.",
    "employers.hero.description": "Comblez les lacunes de compétences avec l'approche moderne du recrutement mondial—traitement plus rapide, coûts réduits et meilleur taux de succès.",
    "employers.hero.cta.primary": "Nous parler",
    "employers.hero.cta.secondary": "Réserver une démo",
    "employers.features.title": "Immipass est la plateforme leader de gestion de l'immigration pour les employeurs",
    "employers.features.subtitle": "Qu'est-ce qu'Immipass",
    "employers.feature1.title": "Recrutement simplifié",
    "employers.feature1.description": "Accélérez le recrutement international avec notre plateforme numérique",
    "employers.feature2.title": "Réduire les coûts",
    "employers.feature2.description": "Réduisez les frais juridiques avec des processus efficaces axés sur la technologie",
    "employers.feature3.title": "Restez conforme",
    "employers.feature3.description": "Une supervision juridique experte assure la conformité aux lois sur l'immigration",
    "employers.feature4.title": "Traitement plus rapide",
    "employers.feature4.description": "Réduisez les délais de traitement avec des flux de travail automatisés",
    "employers.feature5.title": "Retenir les talents",
    "employers.feature5.description": "Soutenez les employés tout au long de leur parcours d'immigration",
    "employers.feature6.title": "Meilleurs taux de succès",
    "employers.feature6.description": "Des conseils experts mènent à de meilleurs résultats",
    "employers.cta.title": "Commencez à recruter des talents mondiaux aujourd'hui",
    "employers.cta.description": "Modernisez votre recrutement international avec Immipass",
    "employers.cta.primary": "Commencer",
    "employers.cta.secondary": "Planifier une démo",

    // Agents Page
    "agents.hero.title": "Donnez à vos étudiants l'avantage d'un soutien juridique fiable et abordable",
    "agents.hero.description": "Offrez des conseils soutenus par des avocats sans changer votre façon de travailler avec les étudiants.",
    "agents.hero.cta.primary": "Créer votre compte agent gratuit",
    "agents.hero.cta.secondary": "Réserver une démo",
    "agents.features.title": "Immipass offre aux agents d'éducation un soutien juridique en immigration fiable et abordable",
    "agents.features.subtitle": "Qu'est-ce qu'Immipass?",
    "agents.feature1.title": "Soutien juridique",
    "agents.feature1.description": "Offrez des conseils soutenus par des avocats sans changer votre façon de travailler avec les étudiants",
    "agents.feature2.title": "Réduire les risques",
    "agents.feature2.description": "Protégez-vous et vos étudiants avec une supervision juridique professionnelle",
    "agents.feature3.title": "Meilleurs résultats",
    "agents.feature3.description": "Aidez vos étudiants à réussir avec un soutien complet en immigration",
    "agents.feature4.title": "Tarification abordable",
    "agents.feature4.description": "Des tarifs compétitifs qui conviennent aux agents et aux étudiants",
    "agents.feature5.title": "Bâtir la confiance",
    "agents.feature5.description": "Renforcez votre réputation avec un soutien juridique professionnel",
    "agents.feature6.title": "Modèle de partenariat",
    "agents.feature6.description": "Continuez à guider les étudiants pendant que nous gérons les complexités juridiques",
    "agents.cta.title": "Devenez partenaire Immipass aujourd'hui",
    "agents.cta.description": "Donnez à vos étudiants le soutien juridique qu'ils méritent",
    "agents.cta.primary": "Créer un compte gratuit",
    "agents.cta.secondary": "En savoir plus",

    // Institutions Page
    "institutions.hero.title": "Votre partenaire pour une meilleure expérience étudiante internationale",
    "institutions.hero.description": "Immipass est la plateforme numérique de référence pour la gestion de l'immigration",
    "institutions.hero.cta.primary": "Devenir partenaire",
    "institutions.hero.cta.secondary": "Réserver une démo",
    "institutions.features.title": "Immipass est la première plateforme de gestion de l'immigration, propulsée par des experts juridiques",
    "institutions.features.subtitle": "Qu'est-ce qu'Immipass",
    "institutions.feature1.title": "Opérations simplifiées",
    "institutions.feature1.description": "Gérez tous les besoins en immigration des étudiants internationaux sur une seule plateforme",
    "institutions.feature2.title": "Succès des étudiants",
    "institutions.feature2.description": "Aidez les étudiants à rester conformes et à réussir tout au long de leur parcours",
    "institutions.feature3.title": "Atténuation des risques",
    "institutions.feature3.description": "Réduisez les risques de conformité avec une supervision juridique experte",
    "institutions.feature4.title": "Meilleure rétention",
    "institutions.feature4.description": "Soutenez les étudiants de l'admission jusqu'à l'obtention du diplôme et au-delà",
    "institutions.feature5.title": "Gain de temps",
    "institutions.feature5.description": "Réduisez la charge administrative de votre bureau international",
    "institutions.feature6.title": "Partenaire de confiance",
    "institutions.feature6.description": "Soutenu par des avocats en immigration de premier plan à travers le Canada",
    "institutions.cta.title": "Transformez l'expérience de vos étudiants internationaux",
    "institutions.cta.description": "Devenez partenaire d'Immipass pour offrir un soutien complet en immigration",
    "institutions.cta.primary": "Planifier une démo",
    "institutions.cta.secondary": "Nous contacter",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
