import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.newcomers": "Newcomers",
    "nav.schools": "Schools",
    "nav.employers": "Employers",
    "nav.agents": "Agents",
    "nav.visa_refusal": "Visa Refusal",
    "nav.visitor_visas": "Visitor Visas",
    "nav.pgwp": "PGWP",
    "nav.express_entry": "Express Entry & PR",
    "nav.iec": "IEC",
    "nav.get_started": "Get started",
    "nav.login": "Log in",
    "nav.account": "Account",
    "nav.sign_out": "Sign out",
    "nav.settings": "Settings",

    // Footer
    "footer.tagline": "Your trusted guide along your immigration journey.",
    "footer.services": "Services",
    "footer.about": "About",
    "footer.legal": "Legal",
    "footer.about_us": "About Us",
    "footer.contact": "Contact Us",
    "footer.careers": "Careers",
    "footer.terms": "Terms of Use",
    "footer.privacy": "Privacy Policy",
    "footer.accessibility": "Accessibility",
    "footer.rights": "All rights reserved.",
    "footer.education_agents": "Education Agents",

    // Index Page
    "index.hero.title": "Your trusted guide along your immigration journey",
    "index.hero.description": "Immipass is the clear and affordable platform for immigration guidance and legal support",
    "index.hero.cta.primary": "Get started",
    "index.hero.cta.secondary": "Talk to us",
    "index.steps.title": "Students, workers, and visitors: Immipass is with you at every step",
    "index.step1.title": "Apply for your visa",
    "index.step1.description": "Navigate the immigration process with clear understanding and automatic updates",
    "index.step2.title": "Submit for lawyer review",
    "index.step2.description": "Get guidance and expertise from expert immigration lawyers",
    "index.step3.title": "Stay organized",
    "index.step3.description": "Keep your critical documents organized in your personal Document Vault",
    "index.step4.title": "Continue your journey",
    "index.step4.description": "Plan your path to permanent residence with expert legal guidance",
    "index.features.title": "Exclusive benefits for Immipass Members",
    "index.features.subtitle": "Why Immipass?",
    "index.feature1.title": "Expert Legal Guidance",
    "index.feature1.description": "Access to leading immigration lawyers helps you navigate the immigration process",
    "index.feature2.title": "Stay Protected",
    "index.feature2.description": "Immipass will remind you of upcoming deadlines and legal updates",
    "index.feature3.title": "Unwavering Support",
    "index.feature3.description": "Licensed immigration lawyers working for you at every stage",
    "index.feature4.title": "Affordable Access",
    "index.feature4.description": "Every application is reviewed by a licensed immigration lawyer",
    "index.feature5.title": "Document Organization",
    "index.feature5.description": "Keep your critical documents organized in your personal vault",
    "index.feature6.title": "Exclusive Benefits",
    "index.feature6.description": "Get great deals on banking, mobile, internet, and more",
    "index.testimonials.title": "Trusted by thousands of international students, newcomers, and institutions",
    "index.testimonial1.quote": "The IRCC portal can be overwhelming to use at times, so I'm grateful that Immipass was able to help with reviewing and submitting my application.",
    "index.testimonial1.author": "Aisha",
    "index.testimonial1.role": "International Student from Nigeria",
    "index.testimonial2.quote": "I have a lot of friends and they already know they are going to use Immipass because it's convenient, interactive and made my life so much easier.",
    "index.testimonial2.author": "Ahmed",
    "index.testimonial2.role": "International Student from Pakistan",
    "index.testimonial3.quote": "I am so thankful to be here in Canada. I'm grateful for the effort, knowledge, and support of Immipass—you helped get me here!",
    "index.testimonial3.author": "Anagha",
    "index.testimonial3.role": "International Student from Kenya",
    "index.cta.title": "Take the next step",
    "index.cta.description": "Become a Immipass member today",
    "index.cta.primary": "Join Immipass",
    "index.cta.secondary": "Get in touch",

    "index.hero.subtitle": "WELCOME",
    "index.how.title": "How the Platform Works",
    "index.how.subtitle": "SIMPLE PROCESS",
    "index.how.step1.title": "Create a profile",
    "index.how.step1.description": "Users securely enter personal background, education, work history, and language results.",
    "index.how.step2.title": "Run the assessment",
    "index.how.step2.description": "A rules-based system compares their profile with major federal and provincial immigration programs.",
    "index.how.step3.title": "Receive an action plan",
    "index.how.step3.description": "Users get a ranked list of suitable programs, explanations, next steps, and the option to consult a professional.",
    "index.paid.title": "Go Further with a Paid Assessment",
    "index.paid.subtitle": "DETAILED ANALYSIS",
    "index.paid.feature1.title": "Ranked Program List",
    "index.paid.feature1.description": "A ranked list of the most relevant immigration programs tailored to your specific profile and goals.",
    "index.paid.feature2.title": "Estimated Scores",
    "index.paid.feature2.description": "Detailed estimated scores for point-based systems like Express Entry to help you understand where you stand.",
    "index.paid.feature3.title": "Strengths & Weaknesses",
    "index.paid.feature3.description": "Comprehensive explanations of the strengths and weaknesses in your profile to identify gaps.",
    "index.paid.feature4.title": "Personalized Advice",
    "index.paid.feature4.description": "Actionable, personalized advice on how to improve your eligibility and increase your points.",
    "index.paid.feature5.title": "Professional Consultation",
    "index.paid.feature5.description": "The option to add a private consultation with a licensed immigration professional at a preferred rate.",
    "index.analyze.title": "What We Analyze",
    "index.analyze.subtitle": "COMPREHENSIVE COVERAGE",
    "index.analyze.feature1.title": "Personal Details",
    "index.analyze.feature1.description": "We collect key personal and family details to ensure accurate eligibility assessment for all family members.",
    "index.analyze.feature2.title": "Education & Language",
    "index.analyze.feature2.description": "Deep dive into your Canadian and foreign education (including ECA status) and language test results.",
    "index.analyze.feature3.title": "Work Experience",
    "index.analyze.feature3.description": "Detailed analysis of your work history both inside and outside Canada to maximize your points.",
    "index.analyze.feature4.title": "Regional Preferences",
    "index.analyze.feature4.description": "We consider your job offers and provincial preferences to match you with the right PNP streams.",
    "index.analyze.feature5.title": "Financial Capacity",
    "index.analyze.feature5.description": "Assessment of your settlement funds and financial capacity to meet program requirements.",
    "index.analyze.feature6.title": "Special Considerations",
    "index.analyze.feature6.description": "We identify complex situations like refugee claims or H&C factors to flag when legal consultation is needed.",
    "index.commitment.title": "Our Commitment to You",
    "index.commitment.subtitle": "TRUST & TRANSPARENCY",
    "index.commitment.feature1.title": "Encrypted Data",
    "index.commitment.feature1.description": "Your data is stored securely with industry-standard encryption. We prioritize the protection of your personal information.",
    "index.commitment.feature2.title": "Privacy First",
    "index.commitment.feature2.description": "We use your personal information strictly for assessments and requested services. Your data is not sold to third parties.",
    "index.commitment.feature3.title": "Bilingual Support",
    "index.commitment.feature3.description": "Full availability in both English and French to support you in the official language of your choice.",
    "index.commitment.feature4.title": "Legal Disclaimer",
    "index.commitment.feature4.description": "This tool is for guidance only. Official immigration decisions are made solely by IRCC and provincial authorities.",

    // Newcomers Page
    "newcomers.hero.title": "Trusted guidance for your immigration journey",
    "newcomers.hero.subtitle": "NEWCOMERS",
    "newcomers.hero.description": "We're here every step of the way. Get guidance and tools for visa applications, study permits, work permits, and more—all with personal support.",
    "newcomers.hero.cta.primary": "Get Started",
    "newcomers.hero.cta.secondary": "Log in now",
    "newcomers.features.title": "We're here every step of the way",
    "newcomers.features.subtitle": "OUR SERVICES",
    "newcomers.feature1.title": "Study Permits",
    "newcomers.feature1.description": "Immipass gives you more clarity and confidence to apply for your Canadian study permit with real legal support at every step. We help you avoid the risks of doing it alone, at a fraction of the cost of traditional legal services.",
    "newcomers.feature2.title": "Work Permits",
    "newcomers.feature2.description": "Immipass helps you apply for your Canadian work permit with added clarity, confidence, and legal support from start to finish. Whether you're starting a new job, switching employers, or restoring your status.",
    "newcomers.feature3.title": "Permanent Residence",
    "newcomers.feature3.description": "Immipass supports your journey to permanent residence with step-by-step legal guidance—so you don't have to figure it out alone. From matching your NOC code to maximizing your CRS points.",
    "newcomers.feature4.title": "Rewards and Offers",
    "newcomers.feature4.description": "Immipass Members get special offers on banking, mobile, internet, and more to help you in your new home—from some of the country's largest and most trusted providers.",
    "newcomers.feature5.title": "Personalized Checklists",
    "newcomers.feature5.description": "Every application is reviewed by licensed immigration lawyers to help catch issues before you submit—so you don't have to figure it out on your own.",
    "newcomers.feature6.title": "Immigration Support",
    "newcomers.feature6.description": "We help support every aspect of your new life with offers for tax filing, credit building, auto leases, loans, and additional settlement services.",
    "newcomers.cta.title": "Exclusive benefits for Immipass Members",
    "newcomers.cta.description": "Get guidance and expertise from expert immigration lawyers to help prepare your strongest application.",
    "newcomers.cta.primary": "Become a Member",

    // Express Entry Page
    "express.hero.title": "Your Fastest Path to Permanent Residence",
    "express.hero.subtitle": "EXPRESS ENTRY",
    "express.hero.description": "Navigate the Express Entry system with confidence. From profile creation to Invitation to Apply, Immipass is with you.",
    "express.hero.cta.primary": "Check Eligibility",
    "express.features.title": "Maximize Your Success",
    "express.features.subtitle": "EXPRESS ENTRY BENEFITS",
    "express.feature1.title": "Path to PR",
    "express.feature1.description": "Understand your eligibility for the three federal programs managed through Express Entry: FSW, FST, and CEC.",
    "express.feature2.title": "Profile Optimization",
    "express.feature2.description": "Maximize your CRS score. We help you identify areas for improvement like language scores or education assessments.",
    "express.feature3.title": "Document Review",
    "express.feature3.description": "Ensure your supporting documents are accurate and complete before you receive an Invitation to Apply (ITA).",
    "express.feature4.title": "Legal Representation",
    "express.feature4.description": "Have a licensed immigration lawyer represent you throughout the process, from profile creation to final PR application.",
    "express.feature5.title": "Draw Updates",
    "express.feature5.description": "Stay informed about the latest Express Entry draws, CRS cut-off scores, and category-based rounds of invitations.",
    "express.feature6.title": "PNP Options",
    "express.feature6.description": "Explore Provincial Nominee Programs that align with your Express Entry profile to boost your chances of selection.",
    "express.cta.title": "Ready to make Canada your home?",
    "express.cta.description": "Create your profile today and see how Immipass can help you achieve Permanent Residence.",
    "express.cta.primary": "Get Started",

    // Institutions Page
    "institutions.hero.title": "Trusted by leading educational institutions & partners",
    "institutions.hero.subtitle": "INSTITUTIONS",
    "institutions.hero.description": "Your partner for a better international student experience. Elevate your school's reputation and support your international students.",
    "institutions.hero.cta": "Partner with Us",
    "institutions.features.title": "How Immipass helps DLIs",
    "institutions.features.subtitle": "FEATURES",
    "institutions.features.private.title": "Private",
    "institutions.features.private.description": "Privacy is paramount in our design. Expertly crafted by legal professionals and software engineers, we prioritize the confidentiality of your institution and student data.",
    "institutions.features.secure.title": "Secure",
    "institutions.features.secure.description": "Trust is the foundation of our security. With SOC 2 certification and secure cloud infrastructure, our platform meets the highest industry standards.",
    "institutions.features.accessible.title": "Accessible",
    "institutions.features.accessible.description": "Immipass is designed for effortless integration with your institution's systems, providing a streamlined experience through single-sign-on functionality.",
    "institutions.features.reputation.title": "Elevate Reputation",
    "institutions.features.reputation.description": "Raise your school's profile by creating a trustworthy, simple, and open process to attract top students. Boost international enrolment with a method supported by Canadian legal know-how.",
    "institutions.features.reports.title": "Detailed Reports",
    "institutions.features.reports.description": "Measure your school's success through detailed reports including data on post-graduation residency and employment.",
    "institutions.features.assistance.title": "Dedicated Assistance",
    "institutions.features.assistance.description": "Keep students engaged and enrolled with dedicated assistance throughout their journey.",
    "institutions.cta.title": "Lets see how we can work together",
    "institutions.cta.description": "Immipass is designed for effortless integration with your institution's systems.",
    "institutions.cta.primary": "Schedule a Demo",
    "institutions.cta.secondary": "Contact Us",

    // Employers Page
    "employers.hero.title": "Optimize International Hiring. Reduce Costs. Stay Compliant.",
    "employers.hero.subtitle": "EMPLOYERS",
    "employers.hero.description": "The premier immigration management platform for employers. Enable a global workforce and stay compliant with regulatory requirements.",
    "employers.hero.cta": "Book a Demo",
    "employers.features.title": "Why Employers Choose Immipass",
    "employers.features.subtitle": "BENEFITS",
    "employers.features.gap.title": "Close Skills Gap",
    "employers.features.gap.description": "Secure critical hires quickly and efficiently. Access pre-vetted, work-ready talent to fill you labour needs.",
    "employers.features.costs.title": "Reduce Costs",
    "employers.features.costs.description": "Reduce legal and administrative costs. Scale international hiring with ease and a unified platform.",
    "employers.features.compliant.title": "Stay Compliant",
    "employers.features.compliant.description": "Stay audit-ready with real-time compliance oversight. Streamline visa management and documentation.",
    "employers.features.guidance.title": "Expert Guidance",
    "employers.features.guidance.description": "Work Permits, Express Entry Applications, LMIA, Provincial Nominee Programs (PNP), and Permanent Residency Pathways.",
    "employers.features.growth.title": "Focus on Growth",
    "employers.features.growth.description": "Retain top talent by supporting their long-term immigration goals. Fast-track permanent residency for key hires.",
    "employers.features.workforce.title": "Global Workforce",
    "employers.features.workforce.description": "Enable a global workforce and stay compliant. Enhance success rates for extensions, reviews, and appeals.",
    "employers.cta.title": "Ready to simplify your international hiring?",
    "employers.cta.description": "Book a call with our team to learn how we can help you scale your workforce.",
    "employers.cta.primary": "Contact Sales",

    // Agents Page
    "agents.hero.title": "Empower Your Agency with Legal Tech",
    "agents.hero.subtitle": "AGENTS",
    "agents.hero.description": "The trusted platform for education agents. Ensure compliance, increase success rates, and scale your business with Immipass.",
    "agents.hero.cta": "Partner with Us",
    "agents.features.title": "Why Agents Choose Immipass",
    "agents.features.subtitle": "BENEFITS",
    "agents.features.compliance.title": "Legal Compliance",
    "agents.features.compliance.description": "Ensure all applications meets the latest regulatory requirements. Reduce the risk of refusals with lawyer-backed reviews.",
    "agents.features.risk.title": "Risk Mitigation",
    "agents.features.risk.description": "Protect your reputation and your clients with our verifiable, secure platform. Avoid unauthorized representation issues.",
    "agents.features.management.title": "Client Management",
    "agents.features.management.description": "Manage all your student and client applications in one dashboard. Track status, documents, and communications easily.",
    "agents.features.revenue.title": "Revenue Growth",
    "agents.features.revenue.description": "Expand your service offerings with admitted legal support. Earn commission on value-added services.",
    "agents.features.success.title": "Higher Success Rates",
    "agents.features.success.description": "Leverage our data-driven approach and legal expertise to improve visa approval rates for your clients.",
    "agents.features.partnership.title": "Trusted Partnership",
    "agents.features.partnership.description": "Partner with a Canadian law firm to offer regulated immigration advice without being a lawyer yourself.",
    "agents.cta.title": "Ready to scale your business?",
    "agents.cta.description": "Join the network of top agents using Immipass to deliver better results for their students.",
    "agents.cta.primary": "Contact Us",

    // Visa Refusal Page
    "refusal.hero.title": "Get Help After a Visa Refusal",
    "refusal.hero.subtitle": "VISA REFUSAL",
    "refusal.hero.description": "If your study permit, work permit, or other visa was refused, Immipass will help you learn why, and explore all available options for approval.",
    "refusal.hero.cta": "Find Path Forward",
    "refusal.features.title": "Find the Best Path Forward",
    "refusal.features.subtitle": "SOLUTIONS",
    "refusal.features.reconsideration.title": "Request Reconsideration",
    "refusal.features.reconsideration.description": "If key details were missed in your original application, or if there was an error in processing, we can help you request a reconsideration to get your application back on track.",
    "refusal.features.analysis.title": "Detailed Analysis",
    "refusal.features.analysis.description": "Immipass will help you learn why your application was refused. We analyze the refusal letter and officer notes to determine the best strategy.",
    "refusal.features.reapply.title": "Reapply with Strength",
    "refusal.features.reapply.description": "Reapply with a stronger case using our expert guidance. We help you address the specific concerns raised by the immigration officer.",
    "refusal.features.review.title": "Judicial Review",
    "refusal.features.review.description": "Seek a judicial review to challenge an unfair refusal. Our legal team can represent you in Federal Court if the decision was unreasonable.",
    "refusal.features.support.title": "Expert Legal Support",
    "refusal.features.support.description": "Immipass is the lawyer-backed digital platform designed to make immigration clearer and more affordable, especially when facing complex refusals.",
    "refusal.features.options.title": "Explore Options",
    "refusal.features.options.description": "Don't give up. We help you explore all available options for approval, ensuring you have the best chance of success moving forward.",
    "refusal.cta.title": "Don't let a refusal stop your journey",
    "refusal.cta.description": "Get expert legal help to challenge the decision or submit a stronger application.",
    "refusal.cta.primary": "Get Help Now",

    // Visitor Visas Page
    "visitor.hero.title": "Travel with Confidence: Buyer Your Visitor Visa",
    "visitor.hero.subtitle": "VISITOR VISAS",
    "visitor.hero.description": "Apply for Your Visitor Visa or Super Visa with Immipass. Expert affordable legal support for your trip to Canada.",
    "visitor.hero.cta": "Apply Now",
    "visitor.features.title": "Why choose Immipass?",
    "visitor.features.subtitle": "BENEFITS",
    "visitor.features.support.title": "Expert Support",
    "visitor.features.support.description": "Apply with confidence on the platform backed by certified immigration lawyers. We assume your application meets all requirements for a smoother approval process.",
    "visitor.features.family.title": "Family & Friends",
    "visitor.features.family.description": "Reunite with family and friends in Canada. We guide you through crafting invitation letters and preparing essential documents to show strong ties.",
    "visitor.features.tourism.title": "Tourism & Business",
    "visitor.features.tourism.description": "Canada's natural wonders and vibrant cities await. Immipass helps ensure your itinerary and documentation showcase your trip's purpose clearly.",
    "visitor.features.supervisa.title": "Super Visas",
    "visitor.features.supervisa.description": "For parents and grandparents. Stay for up to 5 years at a time. We help ensure your application meets financial, medical, and eligibility requirements.",
    "visitor.features.study.title": "Short-Term Study",
    "visitor.features.study.description": "For Visiting Research Scholars or short-term exchanges less than 6 months. Ensure endorsements and support letters are correct.",
    "visitor.features.membership.title": "Free Membership",
    "visitor.features.membership.description": "Apply for your visitor visa and receive a free one-year Immipass Membership ($120 value) for continued support and exclusive offers.",
    "visitor.cta.title": "Start your Canadian adventure",
    "visitor.cta.description": "Travel with confidence knowing your application has been reviewed by experts.",
    "visitor.cta.primary": "Start Application",

    // PGWP Page
    "pgwp.hero.title": "Apply for your PGWP the Smarter Way",
    "pgwp.hero.subtitle": "POST-GRAD WORK PERMIT",
    "pgwp.hero.description": "You did the hard part—now let us handle the paperwork. Get expert legal review and start working sooner.",
    "pgwp.hero.cta": "Apply for PGWP",
    "pgwp.features.title": "One Platform from PGWP to PR",
    "pgwp.features.subtitle": "WHY CHOOSE Immipass",
    "pgwp.features.review.title": "Expert Legal Review",
    "pgwp.features.review.description": "Your PGWP application is reviewed by licensed immigration lawyers to help catch issues and submit a strong, complete application.",
    "pgwp.features.guidance.title": "Step-by-Step Guidance",
    "pgwp.features.guidance.description": "Navigate your PGWP application with confidence. Personalized checklists, smart reminders, and clear instructions so you know what's next.",
    "pgwp.features.working.title": "Start Working ASAP",
    "pgwp.features.working.description": "Get a personalized legal letter to share with your employer so you can start working with confidence without risking your status.",
    "pgwp.features.tools.title": "Smart Job Tools",
    "pgwp.features.tools.description": "Find jobs that support your long-term plans. Our AI tools focus on roles aligned with your NOC code for future PR options.",
    "pgwp.features.savings.title": "Savings for PR",
    "pgwp.features.savings.description": "Your PGWP fees carry forward as a credit toward PR planning. Save money as you move from work to permanent residence.",
    "pgwp.features.support.title": "Long-term Support",
    "pgwp.features.support.description": "Immipass stays with you beyond PGWP. Get continued guidance and legal support in one place for your future in Canada.",
    "pgwp.cta.title": "Secure your work status today",
    "pgwp.cta.description": "Apply with confidence and plan your path to Permanent Residence.",
    "pgwp.cta.primary": "Get Started",

    // IEC Page
    "iec.hero.title": "International Experience Canada",
    "iec.hero.subtitle": "IEC",
    "iec.hero.description": "Travel in Canada on a Working Holiday with IEC. Get clear guidance, understand requirements, and get legal support.",
    "iec.hero.cta": "Check Eligibility",
    "iec.features.title": "Work and Travel in Canada",
    "iec.features.subtitle": "PROGRAMS",
    "iec.features.holiday.title": "Working Holiday",
    "iec.features.holiday.description": "Travel and work in Canada. We help you understand the requirements and apply for your work permit so you can explore the country.",
    "iec.features.affordable.title": "Affordable",
    "iec.features.affordable.description": "See if you're eligible at no cost, then apply to the IEC pool for just $75. Professional support that fits your travel budget.",
    "iec.features.guidance.title": "Clear Guidance",
    "iec.features.guidance.description": "Understand the complex requirements. We monitor your application and provide legal support so you can focus on your move to Canada.",
    "iec.features.young.title": "Young Professionals",
    "iec.features.young.description": "Gain Canadian professional work experience to better compete in a global economy. We help with employer-specific work permits.",
    "iec.features.coop.title": "International Co-op",
    "iec.features.coop.description": "Get valuable overseas work experience related to your field of study. Valid for students registered at a post-secondary institution.",
    "iec.features.check.title": "Eligibility Check",
    "iec.features.check.description": "Not sure if you qualify? Use our tools to check your eligibility for the various IEC pools before you apply.",
    "iec.cta.title": "Start your Canadian adventure",
    "iec.cta.description": "Apply to the International Experience Canada pool today with expert support.",
    "iec.cta.primary": "Apply Now",

    // Membership Page
    "membership.title": "Join Immipass Today",
    "membership.description": "Choose the plan that's right for your immigration journey. All plans include access to our platform and community.",
    "membership.plans.basic.name": "Basic",
    "membership.plans.basic.price": "$0",
    "membership.plans.basic.period": "to start",
    "membership.plans.basic.description": "Get started with basic immigration tools",
    "membership.plans.basic.cta": "Get Started Free",
    "membership.plans.member.name": "Member",
    "membership.plans.member.price": "$99",
    "membership.plans.member.period": "per application",
    "membership.plans.member.description": "Full support for your immigration application",
    "membership.plans.member.cta": "Become a Member",
    "membership.plans.premium.name": "Premium",
    "membership.plans.premium.price": "$299",
    "membership.plans.premium.period": "per application",
    "membership.plans.premium.description": "Comprehensive legal support",
    "membership.plans.premium.cta": "Get Premium",
    "membership.plans.features.tracker": "Immigration timeline tracker",
    "membership.plans.features.checklist": "Document checklist",
    "membership.plans.features.email": "Email support",
    "membership.plans.features.kb": "Knowledge base access",
    "membership.plans.features.basic_all": "Everything in Basic",
    "membership.plans.features.lawyer": "Licensed lawyer review",
    "membership.plans.features.guidance": "Personalized guidance",
    "membership.plans.features.vault": "Document vault",
    "membership.plans.features.priority": "Priority support",
    "membership.plans.features.tracking": "Application tracking",
    "membership.plans.features.member_all": "Everything in Member",
    "membership.plans.features.consultation": "1-on-1 lawyer consultation",
    "membership.plans.features.complex": "Complex case support",
    "membership.plans.features.appeal": "Appeal assistance",
    "membership.plans.features.manager": "Dedicated case manager",
    "membership.plans.features.express": "Express processing",
    "membership.popular": "Most Popular",

    // Settings Page
    "settings.title": "Account Settings",
    "settings.subtitle": "Manage your account information and preferences",
    "settings.info.title": "Account Information",
    "settings.info.description": "Your personal account details",
    "settings.info.email": "Email",
    "settings.info.since": "Member since",
    "settings.danger.title": "Danger Zone",
    "settings.danger.description": "Irreversible actions that will permanently affect your account",
    "settings.danger.delete.title": "Delete Account",
    "settings.danger.delete.description": "Once you delete your account, there is no going back. This will permanently delete:",
    "settings.danger.delete.item1": "Your profile and account information",
    "settings.danger.delete.item2": "All consultation requests and saved data",
    "settings.danger.delete.item3": "Your access to Immipass services",
    "settings.danger.delete.confirm.title": "Are you absolutely sure?",
    "settings.danger.delete.confirm.description": "This action cannot be undone. This will permanently delete your account and remove all your data from our servers.",
    "settings.danger.delete.confirm.instruction": "Type DELETE to confirm",
    "settings.danger.delete.confirm.placeholder": "Type DELETE here",
    "settings.danger.delete.confirm.cancel": "Cancel",
    "settings.danger.delete.confirm.action": "Delete Account",
    "settings.danger.delete.confirm.deleting": "Deleting...",
    "settings.toast.confirm_required.title": "Confirmation required",
    "settings.toast.confirm_required.description": "Please type DELETE to confirm account deletion.",
    "settings.toast.delete_success.title": "Account deleted",
    "settings.toast.delete_success.description": "Your account has been permanently deleted.",

    // Auth Page
    "auth.login.title": "Welcome back",
    "auth.login.description": "Log in to your Immipass account",
    "auth.signup.title": "Create your account",
    "auth.signup.description": "Join Immipass and start your immigration journey",
    "auth.forgot.title": "Reset password",
    "auth.forgot.description": "Enter your email to receive a reset link",
    "auth.update.title": "Update password",
    "auth.update.description": "Enter your new password below",
    "auth.fullName": "Full Name",
    "auth.fullNamePlaceholder": "Your full name",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.createAccount": "Create account",
    "auth.sendReset": "Send reset link",
    "auth.wait": "Please wait...",
    "auth.noAccount": "Don't have an account? ",
    "auth.haveAccount": "Already have an account? ",
    "auth.rememberPassword": "Remember your password? ",
    "auth.signUp": "Sign up",
    "auth.logIn": "Log in",
    "auth.toast.reset_sent.title": "Email sent!",
    "auth.toast.reset_sent.description": "Check your inbox for password reset instructions.",
    "auth.toast.update_success.title": "Password updated!",
    "auth.toast.update_success.description": "Your password has been changed successfully. You are now logged in.",
    "auth.toast.login_welcome.title": "Welcome back!",
    "auth.toast.login_welcome.description": "You have successfully logged in.",
    "auth.toast.signup_success.title": "Account created!",
    "auth.toast.signup_success.description": "Welcome to Immipass. Your account has been created.",
    "auth.error.invalid_login": "Invalid email or password. Please try again.",
    "auth.error.email_registered": "This email is already registered. Please log in instead.",
    "auth.placeholder.email": "you@example.com",
    "auth.validation.email": "Please enter a valid email address",
    "auth.validation.password": "Password must be at least 6 characters",
    "auth.validation.email_required": "Please enter your email address",
    "auth.toast.reset_failed": "Reset failed",
    "auth.toast.update_failed": "Update failed",
    "auth.toast.login_failed": "Login failed",
    "auth.toast.account_exists": "Account exists",
    "auth.toast.signup_failed": "Signup failed",

    // NotFound Page
    "notfound.title": "404 — Not Found",
    "notfound.description": "The page you requested could not be found.",

    // Chat Widget
    "chat.header": "Immipass Assistant",
    "chat.placeholder": "Type a message...",
    "chat.welcome": "Hello! 👋 I'm the Immipass AI assistant. I can help assess your eligibility for Canadian immigration. Would you like to start a quick assessment?",
    "chat.start_option_yes": "Yes, let's start",
    "chat.start_option_no": "No, just browsing",
    "chat.ask_name": "Great! Before we begin, what's your name?",
    "chat.ask_age": "Nice to meet you! How old are you?",
    "chat.ask_edu": "What is your highest level of education?",
    "chat.edu_high_school": "High School",
    "chat.edu_diploma": "Diploma / Certificate",
    "chat.edu_bachelors": "Bachelor's Degree",
    "chat.edu_masters": "Master's / PhD",
    "chat.ask_eca": "Do you have an Educational Credential Assessment (ECA) for your foreign education?",
    "chat.eca_yes": "Yes",
    "chat.eca_no": "No",
    "chat.eca_ca": "Not applicable (Canadian Education)",
    "chat.ask_lang": "Have you taken a language test (IELTS / CELPIP / TEF)? If so, what is your approximate CLB level?",
    "chat.lang_clb9": "CLB 9 or higher",
    "chat.lang_clb7": "CLB 7-8",
    "chat.lang_clbBelow7": "Below CLB 7",
    "chat.lang_none": "Not tested yet",
    "chat.ask_work": "How many years of skilled work experience do you have?",
    "chat.work_none": "None",
    "chat.work_less1": "Less than 1 year",
    "chat.work_1_3": "1-3 years",
    "chat.work_3plus": "3+ years",
    "chat.ask_job": "Do you have a valid job offer in Canada?",
    "chat.ask_family": "Do you have immediate family members (spouse, parents, siblings) living in Canada?",
    "chat.ask_funds": "Do you have proof of settlement funds to support your stay?",
    "chat.ask_complex": "Do you have any refugee claims, humanitarian applications, or removal orders in your history?",
    "chat.ask_contact": "Thank you for the information! To provide you with the best recommendations, may I have your email or phone number? (Optional - type 'skip' to skip)",
    "chat.end_uncertain": "Thank you! Based on your answers, our team will review your profile and get back to you with personalized program recommendations. We'll contact you within 24-48 hours.",
    "chat.end_complex": "Thank you for sharing. Given the complexity of your situation (refugee/humanitarian factors), we strongly recommend booking a private consultation with our legal experts for specialized advice. Our team will review your information and contact you soon.",
    "chat.end_browsing": "No problem! Feel free to browse our site. If you change your mind, we're here to help.",
    "chat.notice.title": "Notice",
    "chat.notice.description": "We received your information but couldn't save it to our system. Please contact us directly.",
  },
  fr: {
    // Navbar
    "nav.newcomers": "Nouveaux arrivants",
    "nav.schools": "Écoles",
    "nav.employers": "Employeurs",
    "nav.agents": "Agents",
    "nav.visa_refusal": "Refus de visa",
    "nav.visitor_visas": "Visas visiteur",
    "nav.pgwp": "PTPD",
    "nav.express_entry": "Entrée express et RP",
    "nav.iec": "EIC",
    "nav.get_started": "Commencer",
    "nav.login": "Connexion",
    "nav.account": "Compte",
    "nav.sign_out": "Déconnexion",
    "nav.settings": "Paramètres",

    // Footer
    "footer.tagline": "Votre guide de confiance tout au long de votre parcours d'immigration.",
    "footer.services": "Services",
    "footer.about": "À propos",
    "footer.legal": "Mentions légales",
    "footer.about_us": "À propos de nous",
    "footer.contact": "Nous contacter",
    "footer.careers": "Carrières",
    "footer.terms": "Conditions d'utilisation",
    "footer.privacy": "Politique de confidentialité",
    "footer.accessibility": "Accessibilité",
    "footer.rights": "Tous droits réservés.",
    "footer.education_agents": "Agents d'éducation",

    // Index Page
    "index.hero.title": "Votre guide de confiance tout au long de votre parcours d'immigration",
    "index.hero.description": "Immipass est la plateforme claire et abordable pour l'orientation en immigration et le soutien juridique",
    "index.hero.cta.primary": "Commencer",
    "index.hero.cta.secondary": "Nous parler",
    "index.steps.title": "Étudiants, travailleurs et visiteurs : Immipass vous accompagne à chaque étape",
    "index.step1.title": "Faites votre demande de visa",
    "index.step1.description": "Naviguez dans le processus d'immigration avec une compréhension claire et des mises à jour automatiques",
    "index.step2.title": "Soumettez pour révision juridique",
    "index.step2.description": "Obtenez des conseils et l'expertise d'avocats spécialisés en immigration",
    "index.step3.title": "Restez organisé",
    "index.step3.description": "Gardez vos documents importants organisés dans votre coffre-fort personnel",
    "index.step4.title": "Poursuivez votre parcours",
    "index.step4.description": "Planifiez votre chemin vers la résidence permanente avec des conseils juridiques experts",
    "index.features.title": "Avantages exclusifs pour les membres Immipass",
    "index.features.subtitle": "Pourquoi Immipass?",
    "index.feature1.title": "Conseils juridiques experts",
    "index.feature1.description": "L'accès à des avocats en immigration de premier plan vous aide à naviguer dans le processus d'immigration",
    "index.feature2.title": "Restez protégé",
    "index.feature2.description": "Immipass vous rappellera les échéances et les mises à jour juridiques",
    "index.feature3.title": "Soutien indéfectible",
    "index.feature3.description": "Des avocats en immigration agréés travaillent pour vous à chaque étape",
    "index.feature4.title": "Accès abordable",
    "index.feature4.description": "Chaque demande est examinée par un avocat en immigration agréé",
    "index.feature5.title": "Organisation des documents",
    "index.feature5.description": "Gardez vos documents importants organisés dans votre coffre-fort personnel",
    "index.feature6.title": "Avantages exclusifs",
    "index.feature6.description": "Obtenez d'excellentes offres sur les services bancaires, mobiles, Internet et plus encore",
    "index.testimonials.title": "Approuvé par des milliers d'étudiants internationaux, de nouveaux arrivants et d'institutions",
    "index.testimonial1.quote": "Le portail d'IRCC peut être parfois difficile à utiliser, je suis donc reconnaissante qu'Immipass ait pu m'aider à réviser et soumettre ma demande.",
    "index.testimonial1.author": "Aisha",
    "index.testimonial1.role": "Étudiante internationale du Nigeria",
    "index.testimonial2.quote": "J'ai beaucoup d'amis et ils savent déjà qu'ils vont utiliser Immipass car c'est pratique, interactif et ça m'a tellement facilité la vie.",
    "index.testimonial2.author": "Ahmed",
    "index.testimonial2.role": "Étudiant international du Pakistan",
    "index.testimonial3.quote": "Je suis tellement reconnaissante d'être ici au Canada. Je suis reconnaissante pour les efforts, les connaissances et le soutien d'Immipass—vous m'avez aidée à arriver ici!",
    "index.testimonial3.author": "Anagha",
    "index.testimonial3.role": "Étudiante internationale du Kenya",
    "index.cta.title": "Passez à l'étape suivante",
    "index.cta.description": "Devenez membre Immipass aujourd'hui",
    "index.cta.primary": "Rejoindre Immipass",
    "index.cta.secondary": "Nous contacter",

    "index.hero.subtitle": "BIENVENUE",
    "index.how.title": "Comment fonctionne la plateforme",
    "index.how.subtitle": "PROCESSUS SIMPLE",
    "index.how.step1.title": "Créez votre profil",
    "index.how.step1.description": "Les utilisateurs saisissent en toute sécurité leurs antécédents personnels, leurs études, leurs antécédents professionnels et leurs résultats linguistiques.",
    "index.how.step2.title": "Lancez l'évaluation",
    "index.how.step2.description": "Un système basé sur des règles compare leur profil aux principaux programmes d'immigration fédéraux et provinciaux.",
    "index.how.step3.title": "Recevez un plan d'action",
    "index.how.step3.description": "Les utilisateurs reçoivent une liste classée des programmes appropriés, des explications, les prochaines étapes et l'option de consulter un professionnel.",
    "index.paid.title": "Allez plus loin avec une évaluation payante",
    "index.paid.subtitle": "ANALYSE DÉTAILLÉE",
    "index.paid.feature1.title": "Liste des programmes classés",
    "index.paid.feature1.description": "Une liste classée des programmes d'immigration les plus pertinents adaptés à votre profil et vos objectifs spécifiques.",
    "index.paid.feature2.title": "Scores estimés",
    "index.paid.feature2.description": "Scores estimés détaillés pour les systèmes basés sur les points comme Entrée express pour vous aider à comprendre où vous vous situez.",
    "index.paid.feature3.title": "Forces et faiblesses",
    "index.paid.feature3.description": "Explications complètes des forces et faiblesses de votre profil pour identifier les lacunes.",
    "index.paid.feature4.title": "Conseils personnalisés",
    "index.paid.feature4.description": "Conseils concrets et personnalisés sur la façon d'améliorer votre admissibilité et d'augmenter vos points.",
    "index.paid.feature5.title": "Consultation professionnelle",
    "index.paid.feature5.description": "L'option d'ajouter une consultation privée avec un professionnel de l'immigration agréé à un tarif préférentiel.",
    "index.analyze.title": "Ce que nous analysons",
    "index.analyze.subtitle": "COUVERTURE COMPLÈTE",
    "index.analyze.feature1.title": "Détails personnels",
    "index.analyze.feature1.description": "Nous collectons les détails personnels et familiaux clés pour assurer une évaluation précise de l'admissibilité pour tous les membres de la famille.",
    "index.analyze.feature2.title": "Éducation et langues",
    "index.analyze.feature2.description": "Analyse approfondie de votre éducation canadienne et étrangère (y compris le statut EDE) et de vos résultats aux tests linguistiques.",
    "index.analyze.feature3.title": "Expérience de travail",
    "index.analyze.feature3.description": "Analyse détaillée de vos antécédents professionnels à l'intérieur et à l'extérieur du Canada pour maximiser vos points.",
    "index.analyze.feature4.title": "Préférences régionales",
    "index.analyze.feature4.description": "Nous prenons en compte vos offres d'emploi et vos préférences provinciales pour vous jumeler aux bons volets du PTP.",
    "index.analyze.feature5.title": "Capacité financière",
    "index.analyze.feature5.description": "Évaluation de vos fonds d'établissement et de votre capacité financière pour répondre aux exigences du programme.",
    "index.analyze.feature6.title": "Considérations spéciales",
    "index.analyze.feature6.description": "Nous identifions les situations complexes comme les demandes de statut de réfugié ou les facteurs CH pour signaler quand une consultation juridique est nécessaire.",
    "index.commitment.title": "Notre engagement envers vous",
    "index.commitment.subtitle": "CONFIANCE ET TRANSPARENCE",
    "index.commitment.feature1.title": "Données cryptées",
    "index.commitment.feature1.description": "Vos données sont stockées en toute sécurité avec un cryptage standard de l'industrie. Nous priorisons la protection de vos informations personnelles.",
    "index.commitment.feature2.title": "Priorité à la vie privée",
    "index.commitment.feature2.description": "Nous utilisons vos informations personnelles strictement pour les évaluations et les services demandés. Vos données ne sont pas vendues à des tiers.",
    "index.commitment.feature3.title": "Soutien bilingue",
    "index.commitment.feature3.description": "Disponibilité totale en anglais et en français pour vous accompagner dans la langue officielle de votre choix.",
    "index.commitment.feature4.title": "Avis juridique",
    "index.commitment.feature4.description": "Cet outil est fourni à titre indicatif uniquement. Les décisions officielles en matière d'immigration sont prises uniquement par IRCC et les autorités provinciales.",

    // Nouveaux arrivants
    "newcomers.hero.title": "Des conseils de confiance pour votre parcours d'immigration",
    "newcomers.hero.subtitle": "NOUVEAUX ARRIVANTS",
    "newcomers.hero.description": "Nous sommes là à chaque étape du processus. Obtenez des conseils et des outils pour les demandes de visa, les permis d'études, les permis de travail et plus encore — le tout avec un soutien personnel.",
    "newcomers.hero.cta.primary": "Commencer",
    "newcomers.hero.cta.secondary": "Se connecter",
    "newcomers.features.title": "Nous sommes là à chaque étape du processus",
    "newcomers.features.subtitle": "NOS SERVICES",
    "newcomers.feature1.title": "Permis d'études",
    "newcomers.feature1.description": "Immipass vous donne plus de clarté et de confiance pour demander votre permis d'études canadien avec un véritable soutien juridique à chaque étape. Nous vous aidons à éviter les risques de le faire seul, à une fraction du coût des services juridiques traditionnels.",
    "newcomers.feature2.title": "Permis de travail",
    "newcomers.feature2.description": "Immipass vous aide à demander votre permis de travail canadien avec plus de clarté, de confiance et un soutien juridique de début à la fin. Que vous commenciez un nouvel emploi, changiez d'employeur ou rétablissiez votre statut.",
    "newcomers.feature3.title": "Résidence permanente",
    "newcomers.feature3.description": "Immipass soutient votre parcours vers la résidence permanente avec des conseils juridiques étape par étape — vous n'avez donc pas à le découvrir seul. De la correspondance de votre code CNP à la maximisation de vos points du CRS.",
    "newcomers.feature4.title": "Récompenses et offres",
    "newcomers.feature4.description": "Les membres d'Immipass bénéficient d'offres spéciales sur les services bancaires, mobiles, Internet et plus encore pour vous aider dans votre nouveau foyer — de la part de certains des fournisseurs les plus importants et les plus fiables du pays.",
    "newcomers.feature5.title": "Listes de contrôle personnalisées",
    "newcomers.feature5.description": "Chaque demande est examinée par des avocats en immigration agréés pour aider à détecter les problèmes avant que vous ne la soumettiez — vous n'avez donc pas à le découvrir par vous-même.",
    "newcomers.feature6.title": "Soutien à l'immigration",
    "newcomers.feature6.description": "Nous aidons à soutenir tous les aspects de votre nouvelle vie avec des offres pour la déclaration de revenus, le renforcement du crédit, les locations d'automobiles, les prêts et des services d'établissement supplémentaires.",
    "newcomers.cta.title": "Avantages exclusifs pour les membres Immipass",
    "newcomers.cta.description": "Obtenez des conseils et de l'expertise d'avocats experts en immigration pour vous aider à préparer votre meilleure demande.",
    "newcomers.cta.primary": "Devenir membre",

    // Entrée express
    "express.hero.title": "Votre chemin le plus rapide vers la résidence permanente",
    "express.hero.subtitle": "ENTRÉE EXPRESS",
    "express.hero.description": "Naviguez dans le système Entrée express en toute confiance. De la création du profil à l'invitation à présenter une demande, Immipass est avec vous.",
    "express.hero.cta.primary": "Vérifier l'admissibilité",
    "express.features.title": "Maximisez votre succès",
    "express.features.subtitle": "AVANTAGES DE L'ENTRÉE EXPRESS",
    "express.feature1.title": "Chemin vers la RP",
    "express.feature1.description": "Comprenez votre admissibilité aux trois programmes fédéraux gérés par Entrée express : FSW, FST et CEC.",
    "express.feature2.title": "Optimisation du profil",
    "express.feature2.description": "Maximisez votre score du CRS. Nous vous aidons à identifier les domaines à améliorer, comme les résultats linguistiques ou les évaluations de l'éducation.",
    "express.feature3.title": "Révision des documents",
    "express.feature3.description": "Assurez-vous que vos documents de soutien sont exacts et complets avant de recevoir une invitation à présenter une demande (IPD).",
    "express.feature4.title": "Représentation légale",
    "express.feature4.description": "Faites-vous représenter par un avocat en immigration agréé tout au long du processus, de la création du profil à la demande finale de RP.",
    "express.feature5.title": "Mises à jour des tirages",
    "express.feature5.description": "Restez informé des derniers tirages de l'Entrée express, des scores de coupure du CRS et des rondes d'invitations basées sur les catégories.",
    "express.feature6.title": "Options du PCP",
    "express.feature6.description": "Explorez les programmes des candidats des provinces qui correspondent à votre profil d'Entrée express pour augmenter vos chances de sélection.",
    "express.cta.title": "Prêt à faire du Canada votre foyer ?",
    "express.cta.description": "Créez votre profil dès aujourd'hui et voyez comment Immipass peut vous aider à obtenir la résidence permanente.",
    "express.cta.primary": "Commencer",


    // Institutions Page
    "institutions.hero.title": "Approuvé par des institutions d'enseignement et des partenaires de premier plan",
    "institutions.hero.subtitle": "INSTITUTIONS",
    "institutions.hero.description": "Votre partenaire pour une meilleure expérience des étudiants internationaux. Élevez la réputation de votre école et soutenez vos étudiants internationaux.",
    "institutions.hero.cta": "Devenir partenaire",
    "institutions.features.title": "Comment Immipass aide les EAD",
    "institutions.features.subtitle": "CARACTÉRISTIQUES",
    "institutions.features.private.title": "Privé",
    "institutions.features.private.description": "La confidentialité est primordiale dans notre conception. Conçu par des professionnels du droit et des ingénieurs logiciels, nous privilégions la confidentialité des données de votre établissement et de vos étudiants.",
    "institutions.features.secure.title": "Sécurisé",
    "institutions.features.secure.description": "La confiance est le fondement de notre sécurité. Avec la certification SOC 2 et une infrastructure infonuagique sécurisée, notre plateforme répond aux normes les plus élevées de l'industrie.",
    "institutions.features.accessible.title": "Accessible",
    "institutions.features.accessible.description": "Immipass est conçu pour une intégration sans effort avec les systèmes de votre établissement, offrant une expérience simplifiée grâce à la fonctionnalité de signature unique.",
    "institutions.features.reputation.title": "Élever la réputation",
    "institutions.features.reputation.description": "Rehaussez le profil de votre école en créant un processus fiable, simple et ouvert pour attirer les meilleurs étudiants. Boostez le recrutement international avec une méthode soutenue par le savoir-faire juridique canadien.",
    "institutions.features.reports.title": "Rapports détaillés",
    "institutions.features.reports.description": "Mesurez le succès de votre école grâce à des rapports détaillés incluant des données sur la résidence et l'emploi après l'obtention du diplôme.",
    "institutions.features.assistance.title": "Assistance dédiée",
    "institutions.features.assistance.description": "Gardez les étudiants engagés et inscrits grâce à une assistance dédiée tout au long de leur parcours.",
    "institutions.cta.title": "Voyons comment nous pouvons travailler ensemble",
    "institutions.cta.description": "Immipass est conçu pour une intégration sans effort avec les systèmes de votre établissement.",
    "institutions.cta.primary": "Planifier une démo",
    "institutions.cta.secondary": "Nous contacter",

    // Employers Page
    "employers.hero.title": "Optimisez l'embauche internationale. Réduisez les coûts. Restez conforme.",
    "employers.hero.subtitle": "EMPLOYEURS",
    "employers.hero.description": "La première plateforme de gestion de l'immigration pour les employeurs. Permettez une main-d'œuvre mondiale et restez conforme aux exigences réglementaires.",
    "employers.hero.cta": "Réserver une démo",
    "employers.features.title": "Pourquoi les employeurs choisissent Immipass",
    "employers.features.subtitle": "AVANTAGES",
    "employers.features.gap.title": "Combler le manque de compétences",
    "employers.features.gap.description": "Sécurisez rapidement et efficacement les recrues critiques. Accédez à des talents pré-vérifiés et prêts à travailler pour répondre à vos besoins de main-d'œuvre.",
    "employers.features.costs.title": "Réduire les coûts",
    "employers.features.costs.description": "Réduisez les coûts juridiques et administratifs. Étendez l'embauche internationale avec facilité grâce à une plateforme unifiée.",
    "employers.features.compliant.title": "Rester conforme",
    "employers.features.compliant.description": "Soyez prêt pour les audits avec une surveillance de la conformité en temps réel. Simplifiez la gestion des visas et la documentation.",
    "employers.features.guidance.title": "Conseils d'experts",
    "employers.features.guidance.description": "Permis de travail, demandes Entrée express, EIMT, Programmes des candidats des provinces (PCP) et parcours vers la résidence permanente.",
    "employers.features.growth.title": "Priorité à la croissance",
    "employers.features.growth.description": "Retenez les meilleurs talents en soutenant leurs objectifs d'immigration à long terme. Accélérez la résidence permanente pour les recrues clés.",
    "employers.features.workforce.title": "Main-d'œuvre mondiale",
    "employers.features.workforce.description": "Permettez une main-d'œuvre mondiale et restez conforme. Améliorez les taux de réussite pour les extensions, les révisions et les appels.",
    "employers.cta.title": "Prêt à simplifier votre embauche internationale ?",
    "employers.cta.description": "Réservez un appel avec notre équipe pour apprendre comment nous pouvons vous aider à étendre votre main-d'œuvre.",
    "employers.cta.primary": "Contacter les ventes",

    // Agents Page
    "agents.hero.title": "Donnez du pouvoir à votre agence avec la technologie juridique",
    "agents.hero.subtitle": "AGENTS",
    "agents.hero.description": "La plateforme de confiance pour les agents d'éducation. Assurez la conformité, augmentez les taux de réussite et développez votre entreprise avec Immipass.",
    "agents.hero.cta": "Devenir partenaire",
    "agents.features.title": "Pourquoi les agents choisissent Immipass",
    "agents.features.subtitle": "AVANTAGES",
    "agents.features.compliance.title": "Conformité légale",
    "agents.features.compliance.description": "Assurez-vous que toutes les demandes répondent aux dernières exigences réglementaires. Réduisez le risque de refus grâce à des révisions soutenues par des avocats.",
    "agents.features.risk.title": "Atténuation des risques",
    "agents.features.risk.description": "Protégez votre réputation et vos clients grâce à notre plateforme vérifiable et sécurisée. Évitez les problèmes de représentation non autorisée.",
    "agents.features.management.title": "Gestion des clients",
    "agents.features.management.description": "Gérez toutes vos demandes d'étudiants et de clients dans un seul tableau de bord. Suivez l'état, les documents et les communications facilement.",
    "agents.features.revenue.title": "Croissance des revenus",
    "agents.features.revenue.description": "Élargissez votre offre de services avec un soutien juridique reconnu. Gagnez des commissions sur les services à valeur ajoutée.",
    "agents.features.success.title": "Taux de réussite plus élevés",
    "agents.features.success.description": "Tirez parti de notre approche axée sur les données et de notre expertise juridique pour améliorer les taux d'approbation des visas pour vos clients.",
    "agents.features.partnership.title": "Partenariat de confiance",
    "agents.features.partnership.description": "Associez-vous à un cabinet d'avocats canadien pour offrir des conseils réglementés en immigration sans être vous-même avocat.",
    "agents.cta.title": "Prêt à développer votre entreprise ?",
    "agents.cta.description": "Rejoignez le réseau des meilleurs agents utilisant Immipass pour offrir de meilleurs résultats à leurs étudiants.",
    "agents.cta.primary": "Nous contacter",

    // Visa Refusal Page
    "refusal.hero.title": "Obtenir de l'aide après un refus de visa",
    "refusal.hero.subtitle": "REFUS DE VISA",
    "refusal.hero.description": "Si votre permis d'études, de travail ou un autre visa a été refusé, Immipass vous aidera à comprendre pourquoi et à explorer toutes les options d'approbation.",
    "refusal.hero.cta": "Trouver une issue",
    "refusal.features.title": "Trouver la meilleure voie à suivre",
    "refusal.features.subtitle": "SOLUTIONS",
    "refusal.features.reconsideration.title": "Demande de réexamen",
    "refusal.features.reconsideration.description": "Si des détails clés ont été omis dans votre demande initiale, ou s'il y a eu une erreur de traitement, nous pouvons vous aider à demander un réexamen.",
    "refusal.features.analysis.title": "Analyse détaillée",
    "refusal.features.analysis.description": "Immipass vous aidera à comprendre pourquoi votre demande a été refusée. Nous analysons la lettre de refus et les notes de l'agent pour déterminer la meilleure stratégie.",
    "refusal.features.reapply.title": "Représentation avec force",
    "refusal.features.reapply.description": "Faites une nouvelle demande avec un dossier plus solide grâce à nos conseils d'experts. Nous vous aidons à répondre spécifiquement aux préoccupations de l'agent.",
    "refusal.features.review.title": "Révision judiciaire",
    "refusal.features.review.description": "Demandez une révision judiciaire pour contester un refus injuste. Notre équipe juridique peut vous représenter devant la Cour fédérale.",
    "refusal.features.support.title": "Soutien juridique expert",
    "refusal.features.support.description": "Immipass est la plateforme numérique soutenue par des avocats conçue pour rendre l'immigration plus claire et plus abordable.",
    "refusal.features.options.title": "Explorer les options",
    "refusal.features.options.description": "N'abandonnez pas. Nous vous aidons à explorer toutes les options disponibles pour obtenir une approbation.",
    "refusal.cta.title": "Ne laissez pas un refus arrêter votre parcours",
    "refusal.cta.description": "Obtenez l'aide d'experts juridiques pour contester la décision ou soumettre une demande plus solide.",
    "refusal.cta.primary": "Obtenir de l'aide maintenant",

    // Visitor Visas Page
    "visitor.hero.title": "Voyagez en toute confiance : Obtenez votre visa de visiteur",
    "visitor.hero.subtitle": "VISAS DE VISITEUR",
    "visitor.hero.description": "Demandez votre visa de visiteur ou votre super visa avec Immipass. Soutien juridique expert et abordable pour votre voyage au Canada.",
    "visitor.hero.cta": "Demander maintenant",
    "visitor.features.title": "Pourquoi choisir Immipass ?",
    "visitor.features.subtitle": "AVANTAGES",
    "visitor.features.support.title": "Soutien d'experts",
    "visitor.features.support.description": "Demandez en toute confiance sur la plateforme soutenue par des avocats en immigration certifiés. Nous nous assurons que votre demande réponde à toutes les exigences.",
    "visitor.features.family.title": "Famille et amis",
    "visitor.features.family.description": "Retrouvez votre famille et vos amis au Canada. Nous vous guidons dans la rédaction des lettres d'invitation et la préparation des documents essentiels.",
    "visitor.features.tourism.title": "Tourisme et affaires",
    "visitor.features.tourism.description": "Les merveilles naturelles et les villes dynamiques du Canada vous attendent. Immipass vous aide à assurer que votre itinéraire et votre documentation sont clairs.",
    "visitor.features.supervisa.title": "Super Visas",
    "visitor.features.supervisa.description": "Pour les parents et grands-parents. Restez jusqu'à 5 ans à la fois. Nous nous assurons que votre demande réponde aux exigences financières et médicales.",
    "visitor.features.study.title": "Études de courte durée",
    "visitor.features.study.description": "Pour les chercheurs invités ou les échanges de moins de 6 mois. Assurez-vous que les lettres d'approbation et de soutien sont correctes.",
    "visitor.features.membership.title": "Adhésion gratuite",
    "visitor.features.membership.description": "Demandez votre visa de visiteur et recevez une adhésion gratuite d'un an à Immipass (valeur de 120 $) pour un soutien continu.",
    "visitor.cta.title": "Commencez votre aventure canadienne",
    "visitor.cta.description": "Voyagez en toute confiance en sachant que votre demande a été examinée par des experts.",
    "visitor.cta.primary": "Commencer la demande",

    // PGWP Page
    "pgwp.hero.title": "Demandez votre PEBP de manière plus intelligente",
    "pgwp.hero.subtitle": "PERMIS DE TRAVAIL POST-DIPLÔME",
    "pgwp.hero.description": "Vous avez fait le plus dur, laissez-nous maintenant nous occuper de la paperasse. Obtenez une révision juridique experte et commencez à travailler plus tôt.",
    "pgwp.hero.cta": "Demander le PEBP",
    "pgwp.features.title": "Une plateforme du PEBP à la RP",
    "pgwp.features.subtitle": "POURQUOI CHOISIR Immipass",
    "pgwp.features.review.title": "Révision juridique experte",
    "pgwp.features.review.description": "Votre demande de PEBP est examinée par des avocats spécialisés pour éviter les problèmes et soumettre un dossier solide.",
    "pgwp.features.guidance.title": "Conseils étape par étape",
    "pgwp.features.guidance.description": "Naviguez dans votre demande de PEBP en toute confiance. Listes de contrôle personnalisées, rappels intelligents et instructions claires.",
    "pgwp.features.working.title": "Commencez à travailler rapidement",
    "pgwp.features.working.description": "Obtenez une lettre juridique personnalisée à partager avec votre employeur pour commencer à travailler en toute confiance.",
    "pgwp.features.tools.title": "Outils d'emploi intelligents",
    "pgwp.features.tools.description": "Trouvez des emplois qui soutiennent vos plans à long terme. Nos outils d'IA se concentrent sur les rôles alignés avec votre code CNP.",
    "pgwp.features.savings.title": "Économies pour la RP",
    "pgwp.features.savings.description": "Vos frais de PEBP sont reportés sous forme de crédit pour la planification de la RP. Économisez de l'argent lors de votre transition.",
    "pgwp.features.support.title": "Soutien à long terme",
    "pgwp.features.support.description": "Immipass reste avec vous au-delà du PEBP. Obtenez des conseils continus et un soutien juridique en un seul endroit.",
    "pgwp.cta.title": "Sécurisez votre statut de travail aujourd'hui",
    "pgwp.cta.description": "Faites votre demande en toute confiance et planifiez votre parcours vers la résidence permanente.",
    "pgwp.cta.primary": "Commencer",

    // IEC Page
    "iec.hero.title": "Expérience internationale Canada",
    "iec.hero.subtitle": "EIC",
    "iec.hero.description": "Voyagez au Canada en vacances-travail avec EIC. Bénéficiez de conseils clairs, comprenez les exigences et obtenez un soutien juridique.",
    "iec.hero.cta": "Vérifier l'admissibilité",
    "iec.features.title": "Travailler et voyager au Canada",
    "iec.features.subtitle": "PROGRAMMES",
    "iec.features.holiday.title": "Vacances-travail",
    "iec.features.holiday.description": "Voyagez et travaillez au Canada. Nous vous aidons à comprendre les exigences et à demander votre permis de travail.",
    "iec.features.affordable.title": "Abordable",
    "iec.features.affordable.description": "Vérifiez votre admissibilité sans frais, puis postulez au bassin EIC pour seulement 75 $. Un soutien professionnel adapté à votre budget.",
    "iec.features.guidance.title": "Conseils clairs",
    "iec.features.guidance.description": "Comprenez les exigences complexes. Nous surveillons votre demande et fournissons un soutien juridique.",
    "iec.features.young.title": "Jeunes professionnels",
    "iec.features.young.description": "Acquérez une expérience professionnelle canadienne pour mieux rivaliser sur le marché mondial. Nous aidons avec les permis liés à un employeur.",
    "iec.features.coop.title": "Stage coop international",
    "iec.features.coop.description": "Obtenez une expérience de travail précieuse à l'étranger liée à votre domaine d'études. Valide pour les étudiants inscrits.",
    "iec.features.check.title": "Vérification de l'admissibilité",
    "iec.features.check.description": "Vous n'êtes pas sûr de vous qualifier ? Utilisez nos outils pour vérifier votre admissibilité avant de postuler.",
    "iec.cta.title": "Commencez votre aventure canadienne",
    "iec.cta.description": "Postulez dès aujourd'hui au bassin Expérience internationale Canada avec le soutien d'experts.",
    "iec.cta.primary": "Postuler maintenant",

    // Membership Page
    "membership.title": "Rejoignez Immipass aujourd'hui",
    "membership.description": "Choisissez le plan qui vous convient le mieux pour votre parcours d'immigration. Tous les plans incluent l'accès à notre plateforme et à notre communauté.",
    "membership.plans.basic.name": "Basique",
    "membership.plans.basic.price": "0 $",
    "membership.plans.basic.period": "pour commencer",
    "membership.plans.basic.description": "Commencez avec des outils d'immigration de base",
    "membership.plans.basic.cta": "Commencer gratuitement",
    "membership.plans.member.name": "Membre",
    "membership.plans.member.price": "99 $",
    "membership.plans.member.period": "par demande",
    "membership.plans.member.description": "Soutien complet pour votre demande d'immigration",
    "membership.plans.member.cta": "Devenir membre",
    "membership.plans.premium.name": "Premium",
    "membership.plans.premium.price": "299 $",
    "membership.plans.premium.period": "par demande",
    "membership.plans.premium.description": "Soutien juridique complet",
    "membership.plans.premium.cta": "Obtenir Premium",
    "membership.plans.features.tracker": "Suivi du calendrier d'immigration",
    "membership.plans.features.checklist": "Liste de contrôle des documents",
    "membership.plans.features.email": "Soutien par courriel",
    "membership.plans.features.kb": "Accès à la base de connaissances",
    "membership.plans.features.basic_all": "Tout ce qui est inclus dans Basique",
    "membership.plans.features.lawyer": "Révision par un avocat agréé",
    "membership.plans.features.guidance": "Conseils personnalisés",
    "membership.plans.features.vault": "Coffre-fort de documents",
    "membership.plans.features.priority": "Soutien prioritaire",
    "membership.plans.features.tracking": "Suivi de la demande",
    "membership.plans.features.member_all": "Tout ce qui est inclus dans Membre",
    "membership.plans.features.consultation": "Consultation 1-on-1 avec avocat",
    "membership.plans.features.complex": "Soutien aux cas complexes",
    "membership.plans.features.appeal": "Aide aux appels",
    "membership.plans.features.manager": "Gestionnaire de cas dédié",
    "membership.plans.features.express": "Traitement express",
    "membership.popular": "Le plus populaire",

    // Settings Page
    "settings.title": "Paramètres du compte",
    "settings.subtitle": "Gérez vos informations de compte et vos préférences",
    "settings.info.title": "Informations du compte",
    "settings.info.description": "Vos détails personnels de compte",
    "settings.info.email": "Courriel",
    "settings.info.since": "Membre depuis",
    "settings.danger.title": "Zone de danger",
    "settings.danger.description": "Actions irréversibles qui affecteront définitivement votre compte",
    "settings.danger.delete.title": "Supprimer le compte",
    "settings.danger.delete.description": "Une fois que vous supprimez votre compte, il n'y a pas de retour en arrière. Cela supprimera définitivement :",
    "settings.danger.delete.item1": "Votre profil et vos informations de compte",
    "settings.danger.delete.item2": "Toutes les demandes de consultation et données sauvegardées",
    "settings.danger.delete.item3": "Votre accès aux services d'Immipass",
    "settings.danger.delete.confirm.title": "Êtes-vous absolument sûr ?",
    "settings.danger.delete.confirm.description": "Cette action ne peut pas être annulée. Cela supprimera définitivement votre compte et supprimera toutes vos données de nos serveurs.",
    "settings.danger.delete.confirm.instruction": "Tapez SUPPRIMER pour confirmer",
    "settings.danger.delete.confirm.placeholder": "Tapez SUPPRIMER ici",
    "settings.danger.delete.confirm.cancel": "Annuler",
    "settings.danger.delete.confirm.action": "Supprimer le compte",
    "settings.danger.delete.confirm.deleting": "Suppression...",
    "settings.toast.confirm_required.title": "Confirmation requise",
    "settings.toast.confirm_required.description": "Veuillez taper SUPPRIMER pour confirmer la suppression du compte.",
    "settings.toast.delete_success.title": "Compte supprimé",
    "settings.toast.delete_success.description": "Votre compte a été supprimé définitivement.",

    // Auth Page
    "auth.login.title": "Bon retour",
    "auth.login.description": "Connectez-vous à votre compte Immipass",
    "auth.signup.title": "Créez votre compte",
    "auth.signup.description": "Rejoignez Immipass et commencez votre parcours d'immigration",
    "auth.forgot.title": "Réinitialiser le mot de passe",
    "auth.forgot.description": "Entrez votre courriel pour recevoir un lien de réinitialisation",
    "auth.update.title": "Mettre à jour le mot de passe",
    "auth.update.description": "Entrez votre nouveau mot de passe ci-dessous",
    "auth.fullName": "Nom complet",
    "auth.fullNamePlaceholder": "Votre nom complet",
    "auth.email": "Courriel",
    "auth.password": "Mot de passe",
    "auth.forgotPassword": "Mot de passe oublié ?",
    "auth.createAccount": "Créer un compte",
    "auth.sendReset": "Envoyer le lien",
    "auth.wait": "Veuillez patienter...",
    "auth.noAccount": "Vous n'avez pas de compte ? ",
    "auth.haveAccount": "Vous avez déjà un compte ? ",
    "auth.rememberPassword": "Vous vous souvenez de votre mot de passe ? ",
    "auth.signUp": "S'inscrire",
    "auth.logIn": "Se connecter",
    "auth.toast.reset_sent.title": "Courriel envoyé !",
    "auth.toast.reset_sent.description": "Vérifiez votre boîte de réception pour les instructions de réinitialisation.",
    "auth.toast.update_success.title": "Mot de passe mis à jour !",
    "auth.toast.update_success.description": "Votre mot de passe a été modifié avec succès. Vous êtes maintenant connecté.",
    "auth.toast.login_welcome.title": "Bon retour !",
    "auth.toast.login_welcome.description": "Vous vous êtes connecté avec succès.",
    "auth.toast.signup_success.title": "Compte créé !",
    "auth.toast.signup_success.description": "Bienvenue chez Immipass. Votre compte a été créé.",
    "auth.error.invalid_login": "Courriel ou mot de passe invalide. Veuillez réessayer.",
    "auth.error.email_registered": "Ce courriel est déjà enregistré. Veuillez vous connecter à la place.",
    "auth.placeholder.email": "vous@exemple.com",
    "auth.validation.email": "Veuillez entrer une adresse courriel valide",
    "auth.validation.password": "Le mot de passe doit comporter au moins 6 caractères",
    "auth.validation.email_required": "Veuillez entrer votre adresse courriel",
    "auth.toast.reset_failed": "Réinitialisation échouée",
    "auth.toast.update_failed": "Mise à jour échouée",
    "auth.toast.login_failed": "Connexion échouée",
    "auth.toast.account_exists": "Le compte existe",
    "auth.toast.signup_failed": "Inscription échouée",

    // NotFound Page
    "notfound.title": "404 — Page non trouvée",
    "notfound.description": "La page que vous avez demandée n'a pas pu être trouvée.",

    // Chat Widget
    "chat.header": "Assistant Immipass",
    "chat.placeholder": "Écrivez un message...",
    "chat.welcome": "Bonjour ! 👋 Je suis l'assistant IA d'Immipass. Je peux vous aider à évaluer votre admissibilité à l'immigration canadienne. Souhaitez-vous commencer une évaluation rapide ?",
    "chat.start_option_yes": "Oui, commençons",
    "chat.start_option_no": "Non, je ne fais que naviguer",
    "chat.ask_name": "Génial ! Avant de commencer, quel est votre nom ?",
    "chat.ask_age": "Ravi de vous rencontrer ! Quel âge avez-vous ?",
    "chat.ask_edu": "Quel est votre niveau de scolarité le plus élevé ?",
    "chat.edu_high_school": "École secondaire",
    "chat.edu_diploma": "Diplôme / Certificat",
    "chat.edu_bachelors": "Baccalauréat",
    "chat.edu_masters": "Maîtrise / Doctorat",
    "chat.ask_eca": "Avez-vous une évaluation des diplômes d'études (ÉDÉ) pour vos études à l'étranger ?",
    "chat.eca_yes": "Oui",
    "chat.eca_no": "Non",
    "chat.eca_ca": "Non applicable (études canadiennes)",
    "chat.ask_lang": "Avez-vous passé un test de langue (IELTS / CELPIP / TEF) ? Si oui, quel est votre niveau NCLC approximatif ?",
    "chat.lang_clb9": "NCLC 9 ou plus",
    "chat.lang_clb7": "NCLC 7-8",
    "chat.lang_clbBelow7": "Moins de NCLC 7",
    "chat.lang_none": "Pas encore testé",
    "chat.ask_work": "Combien d'années d'expérience de travail qualifié avez-vous ?",
    "chat.work_none": "Aucune",
    "chat.work_less1": "Moins de 1 an",
    "chat.work_1_3": "1 à 3 ans",
    "chat.work_3plus": "3 ans et plus",
    "chat.ask_job": "Avez-vous une offre d'emploi valide au Canada ?",
    "chat.ask_family": "Avez-vous des membres de votre famille immédiate (conjoint, parents, frères et sœurs) vivant au Canada ?",
    "chat.ask_funds": "Avez-vous une preuve de fonds d'établissement pour subvenir à vos besoins pendant votre séjour ?",
    "chat.ask_complex": "Avez-vous des demandes d'asile, des demandes humanitaires ou des mesures de renvoi dans votre dossier ?",
    "chat.ask_contact": "Merci pour ces informations ! Pour vous fournir les meilleures recommandations, puis-je avoir votre courriel ou votre numéro de téléphone ? (Facultatif - tapez 'skip' pour passer)",
    "chat.end_uncertain": "Merci ! Sur la base de vos réponses, notre équipe examinera votre profil et vous recontactera avec des recommandations de programmes personnalisées. Nous vous contacterons dans les 24 à 48 heures.",
    "chat.end_complex": "Merci pour le partage. Compte tenu de la complexité de votre situation (facteurs de réfugié/humanitaires), nous vous recommandons fortement de réserver une consultation privée avec nos experts juridiques pour des conseils spécialisés. Notre équipe examinera vos informations et vous contactera bientôt.",
    "chat.end_browsing": "Pas de problème ! N'hésitez pas à parcourir notre site. Si vous changez d'avis, nous sommes là pour vous aider.",
    "chat.notice.title": "Avis",
    "chat.notice.description": "Nous avons reçu vos informations mais n'avons pas pu les enregistrer dans notre système. Veuillez nous contacter directement.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
